var dsAnime = [{
	imgAnime: "https://lh3.googleusercontent.com/-FwR4ll1itks/YYTgRDLWh7I/AAAAAAAAzQQ/RWNC0la-ENwHk4XZy87K553C06UMaY2-QCNcBGAsYHQ/s120/Athanasia.png",
	colorBg: "#559fde"
},{
	imgAnime: "https://lh3.googleusercontent.com/-iLRpOBxPNMY/YYTfDXH_fNI/AAAAAAAAzQI/69pp9-eiso0FGlzFCOaUyca8rg7cTFL8ACNcBGAsYHQ/s120/Makima.png",
	colorBg: "#ea3d4d"
},{
	imgAnime: "https://lh3.googleusercontent.com/-Y2MahsxoZSg/YYTdpF3MNCI/AAAAAAAAzQA/nECbe8a7Uxk0cgWpmzjsgqtYX-yiE48qACNcBGAsYHQ/s120/Sakuma-Ritsu.png",
	colorBg: "#4687c3"
},{
	imgAnime: "https://lh3.googleusercontent.com/-fCdX27lgzpw/YYPVCRr_wWI/AAAAAAAAzNw/j38Ic4DFM1w5yDBPhm7KS1kIwT2Bm10zACNcBGAsYHQ/s120/louis.png",
	colorBg: "#776ec9"
},{
	imgAnime: "https://lh3.googleusercontent.com/-9JUI_Fe4kqI/YYPTdUdNYMI/AAAAAAAAzNg/sFIVgPFcinkqUzerV09mA25HaPwRjSYkACNcBGAsYHQ/s120/luminous-valentine.png",
	colorBg: "#776ec9"
},{
	imgAnime: "https://lh3.googleusercontent.com/-ELV3VAJ0wLY/YYPSq9HXb1I/AAAAAAAAzNU/Y6ZHk83OLtMtsn1Fz2fsBzw41xzsmEf-ACNcBGAsYHQ/s120/adam.png",
	colorBg: "#62c84e"
},{
	imgAnime: "https://lh3.googleusercontent.com/-VIv8_L9B4sw/YYPRult_V_I/AAAAAAAAzM4/ugTEOza5fFUf-4IEOPfeq-HE_g_Ad6LbQCNcBGAsYHQ/s120/sayori.png",
	colorBg: "#ec8f80"
},{
	imgAnime: "https://lh3.googleusercontent.com/--4ZNug7f9Q8/YYPSJsAzWDI/AAAAAAAAzNM/aDvxBjQIIKUzOBFXUA3xTo3pdIo4_TktwCNcBGAsYHQ/s120/natsuki.png",
	colorBg: "#eda2ab"
},{
	imgAnime: "https://1.bp.blogspot.com/-o78BEas_k-I/YRpnXa1FW4I/AAAAAAAAwZE/yit4mL4lDjstn_qpo3LrulUdgc9c3ov6QCNcBGAsYHQ/s120/monika.png",
	colorBg: "#6b6cb3"
},{
	imgAnime: "https://lh3.googleusercontent.com/-AAltfF3Y0nc/YYJM9aocYuI/AAAAAAAAzLg/7yQR-oKy6_A9mlsyG8AlTtLWxwws2-TcgCNcBGAsYHQ/s120/Eula.png",
	colorBg: "#5a8bd7"
},{
	imgAnime: "https://lh3.googleusercontent.com/-XL7oinucd7I/YYJIlPMsVUI/AAAAAAAAzK4/Jw06jIEnvEAxnqyJ08oYJ60QwtNJT6regCNcBGAsYHQ/s120/SOPMOD.png",
	colorBg: "#e1393f"
},{
	imgAnime: "https://lh3.googleusercontent.com/-YbMdguIefkU/YYJIFnFUD8I/AAAAAAAAzKw/o51OjrSWs9Um_ZHdZuM0Z5_u4_i6TZxnwCNcBGAsYHQ/s120/Denki.png",
	colorBg: "#ffc844"
},{
	imgAnime: "https://lh3.googleusercontent.com/-5Li7B9xSV6w/YYJGYZZZwCI/AAAAAAAAzKg/66iiuLQEoEkCOCMMFZITVvATXUHgK_1hQCNcBGAsYHQ/s120/valt-aoi.png",
	colorBg: "#438be2"
},{
	imgAnime: "https://lh3.googleusercontent.com/-gYgGG8n6xOg/YX_JieXszcI/AAAAAAAAzEk/EEunf6spzekm4MksvG9MM0Q35-5z9jIpgCNcBGAsYHQ/s120/Ojou.png",
	colorBg: "#b71e2d"
},{
	imgAnime: "https://lh3.googleusercontent.com/-u6L7TI8d9Y0/YX_H-s6qnuI/AAAAAAAAzEU/dooyKVopz-w8SLP68DpkC3y7JVDU2a3IQCNcBGAsYHQ/s120/Hyakkimaru.png",
	colorBg: "#b8353c"
},{
	imgAnime: "https://lh3.googleusercontent.com/-TPfJtn78dPk/YX_HZYUNWQI/AAAAAAAAzEM/UUsS-5qFAl44wynnvJbn9efabY-FdaunQCNcBGAsYHQ/s120/shu-kurenai.png",
	colorBg: "#b43c4e"
},{
	imgAnime: "https://lh3.googleusercontent.com/-xixAViu0rnE/YX_Fxk2xICI/AAAAAAAAzD8/bX1hSFfZ0rErr2fGPd0B5yPM47d-5c3kwCNcBGAsYHQ/s120/Shinomiya-Kaguya.png",
	colorBg: "#d1373d"
},{
	imgAnime: "https://lh3.googleusercontent.com/-vO_iwFqpuGw/YX54Ty5QNTI/AAAAAAAAzAQ/dmOqCfpQlRAzubEyyd2QFDzonHZIYkBnACNcBGAsYHQ/s120/yae-sakura.png",
	colorBg: "#ec95ae"
},{
	imgAnime: "https://lh3.googleusercontent.com/-nI1CR5pTiRY/YX55b44qKFI/AAAAAAAAzAc/soBMTvcY68EkN9xM4leiYCA95F5G6bvSACNcBGAsYHQ/s120/yae-miko.png",
	colorBg: "#fa8da1"
},{
	imgAnime: "https://lh3.googleusercontent.com/-y_DR37h3wJ4/YX_E_D8LmJI/AAAAAAAAzDo/7Ufyvoq6OyoOSCBMRgT01nzVbA_VqTexgCNcBGAsYHQ/s120/cure-flora.png",
	colorBg: "#ff64d4"
},{
	imgAnime: "https://lh3.googleusercontent.com/-1iX57nLD37A/YX_E_HWUq5I/AAAAAAAAzDg/RxAth0a1j4ogMYxjAtKV0DGf4gpzX16hwCNcBGAsYHQ/s120/cure-mermaid.png",
	colorBg: "#5b9ac9"
},{
	imgAnime: "https://lh3.googleusercontent.com/-zHC1tTBMMcE/YX_FAcgErJI/AAAAAAAAzDs/O5T36sMdd_E5gRjRac2Id8QSNVaAKVnUACNcBGAsYHQ/s120/cure-twinkle.png",
	colorBg: "#fecb40"
},{
	imgAnime: "https://lh3.googleusercontent.com/-meEagHt4JUU/YX_E_fqvjwI/AAAAAAAAzDk/T_ZI_eKvREII1wfScp-9AM5-TghJBW5wACNcBGAsYHQ/s120/cure-scarlet.png",
	colorBg: "#f3365e"
},{
	imgAnime: "https://lh3.googleusercontent.com/-8Z08aytgr8M/YX51sU6xbAI/AAAAAAAAy_s/ZJCvPxzmVTc9jLDFsZyriltSqt7s-Y1EQCNcBGAsYHQ/s120/haruno-haruka.png",
	colorBg: "#f46546"
},{
	imgAnime: "https://lh3.googleusercontent.com/--zDuuZMS530/YX52iKVf2uI/AAAAAAAAy_0/dTe7HVeV-HUHlhhuYXwjzcTRFvYOno2MwCNcBGAsYHQ/s120/kaido-minami.png",
	colorBg: "#52cdf6"
},{
	imgAnime: "https://lh3.googleusercontent.com/-aGQtPKQsvNQ/YX52zUSHpQI/AAAAAAAAy_8/IWv9KO2isV8n0ui31x4T26S7RTe1TF5jQCNcBGAsYHQ/s120/amanogawa-kirara.png",
	colorBg: "#ffc770"
},{
	imgAnime: "https://lh3.googleusercontent.com/-3CYRL6KxvgY/YX53Br8gaJI/AAAAAAAAzAA/JKIeMPyLd2AoSECzJxpbt7oasmkyrM-8QCNcBGAsYHQ/s120/akagi-towa.png",
	colorBg: "#f78480"
},{
	imgAnime: "https://lh3.googleusercontent.com/-i4rOPJed_lY/YX_G81AKkhI/AAAAAAAAzEE/hOiDdd5y5OQUCS98akCcvU7PaWu6jnN6wCNcBGAsYHQ/s120/Kaguya-Madoka.png",
	colorBg: "#79649d"
},{
	imgAnime: "https://lh3.googleusercontent.com/-upDDiiYo-Ms/YX4i7AH5wLI/AAAAAAAAy_g/CfMeuqFPXAQgAUIfeiizSYMd46LgIi14wCNcBGAsYHQ/s120/rin-shima.png",
	colorBg: "#7099d6"
},{
	imgAnime: "https://lh3.googleusercontent.com/-A0JmU2vBqas/YX4hW-PovmI/AAAAAAAAy_I/HEk4MLQ_nS0YtFTlaibeGMVf9oHZrecZgCNcBGAsYHQ/s120/klee.png",
	colorBg: "#d64131"
},{
	imgAnime: "https://lh3.googleusercontent.com/-Rt4w0oV-mjI/YX4gDMxZ9kI/AAAAAAAAy_A/424kyT1_wMEwc8oqqERdpiLdTxyOQCbBQCNcBGAsYHQ/s120/kiana.png",
	colorBg: "#ffb243"
},{
	imgAnime: "https://lh3.googleusercontent.com/-K9Bz2vCU_eg/YX4e-8m2E7I/AAAAAAAAy-4/XRhzVuePfw0F6O7SonhOYJDiRcaxzeHVwCNcBGAsYHQ/s120/komi-san.png",
	colorBg: "#b459cb"
},{
	imgAnime: "https://lh3.googleusercontent.com/-t5p-THDB8o0/YX4epkm_zqI/AAAAAAAAy-s/5jXLmqq0cvQKtQovY0Yy1gzSF3jHPw5qACNcBGAsYHQ/s120/satoshi.png",
	colorBg: "#288ce0"
},{
	imgAnime: "https://lh3.googleusercontent.com/-QINx8LuNbR0/YX4d7UPZruI/AAAAAAAAy-g/2I35CyrgK641K1EZMNtn1A1w4UwDMxhnwCNcBGAsYHQ/s120/arima-kousei.png",
	colorBg: "#5fa9c1"
},{
	imgAnime: "https://1.bp.blogspot.com/-JGrthO2Roh8/YRJ1ubT0qFI/AAAAAAAAwE8/TXJjlZupyOAAcaNrXp-1HnBkRBwr1YCTwCNcBGAsYHQ/s120/kaori-miyazono.png",
	colorBg: "#82778a"
},{
	imgAnime: "https://lh3.googleusercontent.com/-sFp2YB3bp2g/YX4bm1iWDvI/AAAAAAAAy-Y/s644FKJuw2QV2hYeF7YrFUmUYsI8sFf8ACNcBGAsYHQ/s120/kawaki.png",
	colorBg: "#b95768"
},{
	imgAnime: "https://lh3.googleusercontent.com/-amHkN74EZ9I/YX4ZkGoZO6I/AAAAAAAAy-I/Gls-Vd4cvIU5o861gToThwILqoj-hyJ9wCNcBGAsYHQ/s120/starfire.png",
	colorBg: "#af2b38"
},{
	imgAnime: "https://lh3.googleusercontent.com/-EtdR0-4dAzk/YX4Y2fzFskI/AAAAAAAAy-A/RhI1aFV5-TIPid6iZNuQmYV9Q92VldcrwCNcBGAsYHQ/s120/reven.png",
	colorBg: "#855fee"
},{
	imgAnime: "https://lh3.googleusercontent.com/-x6jibRH6XXE/YX0zEJHbLZI/AAAAAAAAy9s/21541bg65BAoCUNgoeZsV7dFp0RvSwNmACNcBGAsYHQ/s120/ayano-aishi.png",
	colorBg: "#425cba"
},{
	imgAnime: "https://lh3.googleusercontent.com/-68INF7MjzIY/YX0wYqJOE3I/AAAAAAAAy9c/VHKeEFbQmFYu2ANTOQMmQLyl0GZRzKANQCNcBGAsYHQ/s120/nastuki.png",
	colorBg: "#f089ae"
},{
	imgAnime: "https://lh3.googleusercontent.com/-8fmUCPgWc4g/YX0vcNGbiAI/AAAAAAAAy9U/l0vqaH1Xgy81QM5v6EA0-L5Jr5H_HsLCACNcBGAsYHQ/s120/saiki-kusuo.png",
	colorBg: "#2ec38b"
},{
	imgAnime: "https://lh3.googleusercontent.com/-_QmUGsVWhSE/YX4Z79f9cMI/AAAAAAAAy-Q/QCSddqui_j4np_dkfZX6fx5kSndWWPG2wCNcBGAsYHQ/s120/doraemi.png",
	colorBg: "#fcbc3f"
},{
	imgAnime: "https://lh3.googleusercontent.com/-yyuwJpShasc/YX0unA3-V5I/AAAAAAAAy9M/IVFs7gO1DMMcVsoUJ9Il4igqhSKtWN63QCNcBGAsYHQ/s120/roboko.png",
	colorBg: "#1caabd"
},{
	imgAnime: "https://lh3.googleusercontent.com/-IVq3938YjSY/YXpipcwGi4I/AAAAAAAAy8w/XCpQsR9JtXQVAQO8XlK66GdGD_kDnSCyACNcBGAsYHQ/s120/emiya-shirou.png",
	colorBg: "#3e4588"
},{
	imgAnime: "https://lh3.googleusercontent.com/-FYRkUlH0Zhs/YXpiHe1VGvI/AAAAAAAAy8o/PNcsn9zxYao6AQ2CZsKX1tsf3yzIZWWQACNcBGAsYHQ/s120/renge-miyauchi.png",
	colorBg: "#9990c2"
},{
	imgAnime: "https://lh3.googleusercontent.com/-XiwW2OfHAKE/YXpf7txf1TI/AAAAAAAAy8Y/tVkrhVCJZi0gu5x1CA7kNqCx3wree0DEQCNcBGAsYHQ/s120/fuwa.png",
	colorBg: "#6bd0f1"
},{
	imgAnime: "https://lh3.googleusercontent.com/-oMXVFXyZ-go/YXpcoMLBooI/AAAAAAAAy8E/xIqIG3r1g7UdkrhGVtT-MaEXcGvMHlESACNcBGAsYHQ/s120/tatsuya-shiba.png",
	colorBg: "#48c7aa"
},{
	imgAnime: "https://lh3.googleusercontent.com/-7_1Jv9QjhRI/YXpcoFo1oDI/AAAAAAAAy8A/9zvtgCA92zMOog4v-h1_SdHoLY3yiRusACNcBGAsYHQ/s120/miyuki-shiba.png",
	colorBg: "#48c7aa"
},{
	imgAnime: "https://1.bp.blogspot.com/-D_8PxJ58tYE/YQqczcsSdoI/AAAAAAAAv3U/M9Z4JB8BYD4IN54qgld45M1G2l9NKD54ACNcBGAsYHQ/s120/tanjiro.png",
	colorBg: "#3b9172"
}, {
	imgAnime: "https://1.bp.blogspot.com/-1lzQ9TBEEtA/YQqczRz91DI/AAAAAAAAv3Y/xSE5cIapEx81y-drb8pTFBX5sXytr-DZACNcBGAsYHQ/s120/nezuko.png",
	colorBg: "#ffa6ac"
}, {
	imgAnime: "https://1.bp.blogspot.com/-rMFuWp2MFiA/YRYgnPhwtyI/AAAAAAAAwOQ/r2cGi9q0x5YtevOyRHpRW4nnoMwGI0MZQCNcBGAsYHQ/s120/zenitsu.png",
	colorBg: "#fabd4b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-DZnM8Bi1E5U/YRYieXtGPkI/AAAAAAAAwOg/Uf5Z5I8B1OkfiRf-WsPtmvhhPI2FjpIlwCNcBGAsYHQ/s120/inosuke.png",
	colorBg: "#a58266"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZTW2Ytci2gc/YQkMQ0IycxI/AAAAAAAAv1I/QDnmL3LLZxQ3uj0UpIokrXYX8uwJRgJBgCNcBGAsYHQ/s120/tomioka-giyuu.png",
	colorBg: "#223657"
},{
	imgAnime: "https://1.bp.blogspot.com/-mSeoBZHv-cw/YQkM6De4UUI/AAAAAAAAv1Q/MEr020DjhR8Ob0ioe2vPflEGqtYtpjYPQCNcBGAsYHQ/s120/kocho-shinobu.png",
	colorBg: "#ae9dd9"
},{
	imgAnime: "https://lh3.googleusercontent.com/-x9g2Y6JIfTM/YXpbDhHq8iI/AAAAAAAAy74/C0SsBrVzBewUzrdqlM4e_KpP0QC2HUx1ACNcBGAsYHQ/s120/rengoku-kyojuro.png",
	colorBg: "#f7b431"
},{
	imgAnime: "https://lh3.googleusercontent.com/-umb_ogjyVC8/YXpWhGI_4pI/AAAAAAAAy7Y/4JSlagjti7cjv0tMTAaqd2ZLFeGDCUCmgCNcBGAsYHQ/s120/uzui-tengen.png",
	colorBg: "#d52d2d"
},{
	imgAnime: "https://lh3.googleusercontent.com/-RDGiHxwXE9U/YXpXDAKrQfI/AAAAAAAAy7g/i6eyt1bJjLshbtMWCTL7ZXPmg13gO5iMgCNcBGAsYHQ/s120/kanroji-mitsuri.png",
	colorBg: "#aecd40"
},{
	imgAnime: "https://lh3.googleusercontent.com/-WmY0wk9-6Xc/YXpXW5XyUxI/AAAAAAAAy7o/9KewY8Hlvis0XdFXzcrpyrOUoc3QLhq8ACNcBGAsYHQ/s120/himejima-gyomei.png",
	colorBg: "#9f9a4f"
},{
	imgAnime: "https://1.bp.blogspot.com/-0kFlQv2Y08Q/YRCIBB6CvxI/AAAAAAAAwCk/Nv77gqkCpScc3f9lXVKPnZu6aCRebUhNQCNcBGAsYHQ/s120/tokito-muichiro.png",
	colorBg: "#2c8889"
}, {
	imgAnime: "https://1.bp.blogspot.com/-MbxYZAK69Sg/YUxdnTaMXLI/AAAAAAAAxiA/4OWrWEmJFZYdrO4x2ppe7zMKtPnqf3TNQCNcBGAsYHQ/s120/iguro-obanai.png",
	colorBg: "#5b2eef"
},{
	imgAnime: "https://lh3.googleusercontent.com/-_6UMVFCUdgQ/YXpaHQAFp9I/AAAAAAAAy7w/jjy0e2PFjMQnvmrKBDACAZ0CkG-mIWLsACNcBGAsYHQ/s120/shinazugawa-sanemi.png",
	colorBg: "#669c50"
},{
	imgAnime: "https://lh3.googleusercontent.com/-A25rIwxZMEA/YXpV7pU39kI/AAAAAAAAy7Q/O1VUW0ATgrEk3_0gCWkxmfOnfvf4dZoSQCNcBGAsYHQ/s120/kocho-kanae.png",
	colorBg: "#852dd5"
},{
	imgAnime: "https://1.bp.blogspot.com/-py52JcBDjg0/YSOT7TUQ7pI/AAAAAAAAwl0/PfKoiNsEaLohOE0Mk1ygke6FQCZd2OQhQCNcBGAsYHQ/s120/yoriichi.png",
	colorBg: "#b83b2e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-VnYeh96cxLY/YSOS_DRgI2I/AAAAAAAAwls/X7FgEYMgjkI_N-1WU1Rb-1I-1R4AicdhwCNcBGAsYHQ/s120/kokushibou.png",
	colorBg: "#9c2e32"
},  {
	imgAnime: "https://lh3.googleusercontent.com/-47Wln-QjZ48/YXpVWuZQRiI/AAAAAAAAy7I/m9EGByy8B-gLv8cHPCxiK-9gXYFmc6q_ACNcBGAsYHQ/s120/kanao.png",
	colorBg: "#9e3ff4"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-NYThrDgZYEQ/YX0yOuzRU9I/AAAAAAAAy9k/EXU2o8LxYAkdHZQzUeXAmrMfQTtMp9G6gCNcBGAsYHQ/s120/aoi-kanzaki.png",
	colorBg: "#656fcc"
}, {
	imgAnime: "https://1.bp.blogspot.com/-DqRWFEqlCwM/YS99-o8ickI/AAAAAAAAw5A/25CkdoaSPDA_TR_BUEjsMYQ7RwavDOOdgCNcBGAsYHQ/s120/sabito.png",
	colorBg: "#9b9cc5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-UTKm-6dLGfg/YS9-oyey5cI/AAAAAAAAw5I/t-_pn2SQ5lU2_0_7YjVtGpr5VM0Id0LrACNcBGAsYHQ/s120/makomo.png",
	colorBg: "#ec8aa1"
},  {
	imgAnime: "https://lh3.googleusercontent.com/-3nXCYPprknc/YXpfFHgywOI/AAAAAAAAy8Q/9KD5YgR3uIsUSi3fGJ1QUNRb48XvK34bwCNcBGAsYHQ/s120/muzan.png",
	colorBg: "#f13c1e"
},{
	imgAnime: "https://1.bp.blogspot.com/-xuj_Dk_DwIo/YSzu0bEAk6I/AAAAAAAAw2M/Rpbv5dbTHm4ru3ngvXXfUj9KBxR-Yw2DQCNcBGAsYHQ/s120/akaza.png",
	colorBg: "#df94a7"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-f7Xnirn5ZwY/YXfMWuI1J9I/AAAAAAAAyp0/PHI5k728oqs5hHsCasn4L_T3GihSNoimQCNcBGAsYHQ/s120/sans.png",
	colorBg: "#347fd8"
},{
	imgAnime: "https://lh3.googleusercontent.com/-XztkjBMGyDE/YXfL3E-DClI/AAAAAAAAyps/Lo9Yb4U-n50pkxkZFUjBOKPgp3FuuPwKwCNcBGAsYHQ/s120/senko.png",
	colorBg: "#f5a933"
},{
	imgAnime: "https://lh3.googleusercontent.com/-RACeL_kfkAw/YXaiHI6x3WI/AAAAAAAAyoQ/rjq4QBgQudQWdVGsE-Qb_SBE_uFZUvaawCNcBGAsYHQ/s120/ceres-fauna.png",
	colorBg: "#64c4a7"
},{
	imgAnime: "https://lh3.googleusercontent.com/-yydRoiOkZaQ/YXahPtjJQgI/AAAAAAAAyoI/oH15syxq6OcjNM1sUToOy7TWnzuNAe2gwCNcBGAsYHQ/s120/yuuki-aine.png",
	colorBg: "#5b81d4"
},{
	imgAnime: "https://lh3.googleusercontent.com/-uQ9jr9bs680/YXag7CcQy2I/AAAAAAAAyoA/9lJJRt7GK7sZNsO63z_E1jz5RssVQS9MgCNcBGAsYHQ/s120/minato-mio.png",
	colorBg: "#5b81d4"
},{
	imgAnime: "https://lh3.googleusercontent.com/-Dvt8kuj-Gno/YXageFyWOpI/AAAAAAAAyn4/OpJ0R9Eyi0QSxlX-7QQJ55aFeNzxqc5ygCNcBGAsYHQ/s120/chara.png",
	colorBg: "#70bd6b"
},{
	imgAnime: "https://lh3.googleusercontent.com/-JxnlDlN8Fm0/YXaf9nnVVJI/AAAAAAAAyns/ZIes6EYSBxQRTLQMNPMMD42tHuTonnntACNcBGAsYHQ/s120/futaba-rio.png",
	colorBg: "#ae9e82"
},{
	imgAnime: "https://lh3.googleusercontent.com/-rWIAShlO9vg/YXQBTyFYcFI/AAAAAAAAyk0/fJXpmVb2RuojJMc_APNB20CUsD9KHyxlQCNcBGAsYHQ/s120/souei.png",
	colorBg: "#6b8aad"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-TGA22nV3PnM/YXP_mVEuZKI/AAAAAAAAykU/I5LseemIOCAJf3hufJ7wtiq4654WmEVjgCNcBGAsYHQ/s120/miyamura.png",
	colorBg: "#2397f0"
},{
	imgAnime: "https://lh3.googleusercontent.com/-_CKMldqP13w/YX_Ip1pj_pI/AAAAAAAAzEc/VW29mXeM73cRmwo5EadX3BJV97LQ9MyWgCNcBGAsYHQ/s120/hori.png",
	colorBg: "#ffb72b"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-9SpihUBY-EY/YXK1jtNQ2pI/AAAAAAAAyio/Xn1v7rCkHZkt9H2o9EMs7Euc106QC-y_ACNcBGAsYHQ/s120/lugh.png",
	colorBg: "#6480db"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-EwHGLkkXJHU/YXK1Nbx02lI/AAAAAAAAyig/OXscDQ9dDf0__MxVwSRgU_1oGC29xbrHACNcBGAsYHQ/s120/lala-satalin-deviluke.png",
	colorBg: "#57a5b1"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-B2VXKXZTfyI/YXK0he_w64I/AAAAAAAAyiY/_CX_Z5Vu6hco1ANCjumZyHAFHn5Y7r1HQCNcBGAsYHQ/s120/rudeus.png",
	colorBg: "#eb494a"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-Z9x998tUp6g/YXKzrjCOkLI/AAAAAAAAyiQ/NYBUE_nauGohLh3TNPMZNUWGpma3nosRACNcBGAsYHQ/s120/issei.png",
	colorBg: "#ef3d3e"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-Vkg-WargXtY/YXKzSKy0DcI/AAAAAAAAyiI/Iq6hs6DggVkJuREJ-Wp_fsVvqVM_RVqywCNcBGAsYHQ/s120/rias.png",
	colorBg: "#7656f0"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-j_1QHO6k3qA/YXKD5RxrlLI/AAAAAAAAyiA/HcsXmrcpbjcNS8omLGBE8GF2Ix8txZuNgCNcBGAsYHQ/s120/kuma-bear.png",
	colorBg: "#8ab0e0"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-gBjDGYXYMFw/YXKDJtGXXoI/AAAAAAAAyh4/UVQvNHhuJb0ygHz6R1wHSNF4xZ-Y_0rbgCNcBGAsYHQ/s120/unmei.png",
	colorBg: "#d83e49"
}, {
	imgAnime: "https://1.bp.blogspot.com/-uRFL4Oqz5bE/YVm9-MXe73I/AAAAAAAAx2M/oasK1eU9WgoJJs80sTlKl9-0rxX7otHcQCNcBGAsYHQ/s120/kirito.png",
	colorBg: "#29d0c2"
}, {
	imgAnime: "https://1.bp.blogspot.com/-puDGBCBEpMA/YRKx4G7KMPI/AAAAAAAAwFM/_JNx3_dZ75AOAl9Yi5AK6OBGtWV9q2hQACNcBGAsYHQ/s120/kirito.png",
	colorBg: "#5998a8"
}, {
	imgAnime: "https://1.bp.blogspot.com/-kdZ-a-Ba0Kw/YRKyjigWqNI/AAAAAAAAwFU/4G11nbPJ9HsmqGt2NbQ8SQiUN0esTVfJwCNcBGAsYHQ/s120/asuna.png",
	colorBg: "#f75148"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-PRT1AwFvxBA/YXQAbCsD9sI/AAAAAAAAykc/QrL9eR1l6kIYAdh-OeXQAUL6s7r2kc8awCNcBGAsYHQ/s120/kirito-ggo.png",
	colorBg: "#a15aea"
},{
	imgAnime: "https://lh3.googleusercontent.com/-9nuYYtk_mNc/YX4hxf7bd4I/AAAAAAAAy_Q/bsvTTISOkRIdjGL4dYxXaBW37rqrQTzDACNcBGAsYHQ/s120/yuuki.png",
	colorBg: "#c870d3"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-pKW63zXNHAQ/YXKA-y8OJLI/AAAAAAAAyhw/3jA2jD2OfqogOZifFfvnCdBvTolqDkvHQCNcBGAsYHQ/s120/alice-zuberg.png",
	colorBg: "#f75148"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-_nci5KCmaNs/YWlugrZi5fI/AAAAAAAAyPc/uHTo7Nm4nG0GT6_6FzgyLIt73TZSlFvCACNcBGAsYHQ/s120/asada-shino.png",
	colorBg: "#70cac0"
}, {
	imgAnime: "https://1.bp.blogspot.com/-s1xlBrhVQao/YUXL2QmledI/AAAAAAAAxWM/sjt6BWYBZ2wN6sj_aKDtAsWSnlWkr2-NgCNcBGAsYHQ/s120/eugeo.png",
	colorBg: "#40b6e2"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-bqXSXxzf9Fc/YXKADnuklEI/AAAAAAAAyho/ojG8jRgk0toUjSXTm_0XNTXEIscD69eVACNcBGAsYHQ/s120/kaonashi.png",
	colorBg: "#9c9c9c"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-UinqgAaxi5s/YXJ9PzdF8NI/AAAAAAAAyhY/he8Y4PAMuQUZLE-185pq8ImagmHx1gYzACNcBGAsYHQ/s120/cool-boy.png",
	colorBg: "#e2bc5f"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-8yIoi7BZwnY/YXJ90fZ4_yI/AAAAAAAAyhg/xPpK-XU9BOwsHsUr-yQAKLlHdgSfvCicQCNcBGAsYHQ/s120/cool-boy.png",
	colorBg: "#345763"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-TVFw_BPpaGI/YW6wNO29gCI/AAAAAAAAycM/KLc1YkmkXMA4iXDXXOvbWjTpM9yz5hQ_gCNcBGAsYHQ/s120/adnachiel.png",
	colorBg: "#4242f2"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-8v2j9fuDRbQ/YWwlFr8m9TI/AAAAAAAAyZM/R61pZD4S_2AS6p7NVngGH39MlCu0Ca7FwCNcBGAsYHQ/s120/subaru.png",
	colorBg: "#3cb3d1"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-t-f4TnRAKq4/YWwkrb5hYRI/AAAAAAAAyZE/O8hpW3m7rF452GxzYG3xfYy9tbAGlq5ZACNcBGAsYHQ/s120/pekora.png",
	colorBg: "#738dd8"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-ZorJi_-fRjk/YWwkOCQSxCI/AAAAAAAAyY8/JbZVvb480UUahXaS7e1IFG1LvHzgtlOsACNcBGAsYHQ/s120/nekomata-okayu.png",
	colorBg: "#a151e5"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-WJcvGQku7qQ/YWwjhas2GoI/AAAAAAAAyY0/u6UCjPlcqc4_xGvnwprD4DTldz6auYYXgCNcBGAsYHQ/s120/sleepy-ash.png",
	colorBg: "#58a5d6"
},{
	imgAnime: "https://lh3.googleusercontent.com/-dZkXwlMneVs/YWqw-Mp3MZI/AAAAAAAAyTk/wwt3ZP2RtlgN6QA7NcNkjnr9aVGck4BTwCNcBGAsYHQ/s120/uto-amatsuka.png",
	colorBg: "#3ba9ef"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-iPNp4513VIk/YWY-Yk5jzTI/AAAAAAAAyLo/LlEm6v77bEE8U52wSBVxN6_qoTeDb08pACNcBGAsYHQ/s120/kanata.png",
	colorBg: "#5aaef8"
}, {
	imgAnime: "https://1.bp.blogspot.com/-tbuRFpMmFyI/YTzDb1g0uOI/AAAAAAAAxHg/dt09NqVGi44qkFIFuUz6cBj9QPLWiVxRACNcBGAsYHQ/s120/banchou.png",
	colorBg: "#ff973a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZYHu2lKhmA8/YT8a1vNCYvI/AAAAAAAAxKk/9PwdaCCv28Qbsy_RwegP0-5iFbcNKPKHwCNcBGAsYHQ/s120/kronii.png",
	colorBg: "#deb94a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Iywvi5Mdmg4/YT8aG3xneYI/AAAAAAAAxKc/9GSmwUZ1I0UP1dAilrn8FHzGpq-TzDm9QCNcBGAsYHQ/s120/fubuki.png",
	colorBg: "#31b1e1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Y0xQNjrvRkE/YTzCrwT1oeI/AAAAAAAAxHY/hSXuMA2co6o1PWt8QQeXlDPilOwd77QSwCNcBGAsYHQ/s120/du-ca.png",
	colorBg: "#ff99b6"
}, {
	imgAnime: "https://1.bp.blogspot.com/-BIrM18_ZZL0/YRKw_XC78GI/AAAAAAAAwFE/dYGr-JTSLkI2RwHgv-kOyAra7tnzAaM8gCNcBGAsYHQ/s120/gura.png",
	colorBg: "#5ea9d4"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-3CUg3MRWsQs/YWwi8NNYlYI/AAAAAAAAyYs/M_hU7sXXlxcOvx4XSJUtoH8AfDCY3k6rwCNcBGAsYHQ/s120/baki.png",
	colorBg: "#fc5048"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-ZGuOjR8i_TY/YWtuPxwLiRI/AAAAAAAAyU4/a9ADLbAKT_AOapoUV4pqVmi7sbT-KVq7gCNcBGAsYHQ/s120/chtholly.png",
	colorBg: "#66a4ed"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-K65lJ9gTk6k/YWq4L1rPwGI/AAAAAAAAyUk/7-wpB91p1s4j75FsV56VFPTDEq8AG03WwCNcBGAsYHQ/s120/tracer.png",
	colorBg: "#f8c335"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-pX6k-_3J1QY/YWq6NxjH0dI/AAAAAAAAyUs/q6fPkxTbHVgHacC2A06MbUcymSOaG2LcwCNcBGAsYHQ/s120/genji.png",
	colorBg: "#91c23b"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-oufFl44fHF4/YWq3GUT7k_I/AAAAAAAAyUU/BY5x9sV9sAES5zJRHI9eEnGVLy1uu8CjwCNcBGAsYHQ/s120/dva.png",
	colorBg: "#f6899c"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-u5ur2u5Wny0/YXaafSFqgDI/AAAAAAAAyng/S_33FDwjmnwD_ZFIl8H6f7-5SG92q9mCACNcBGAsYHQ/s120/sagiri.png",
	colorBg: "#32d3be"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-C9OJUGY7A7U/YWq18oIviqI/AAAAAAAAyUE/9VZTlkEXQEM_RCjyyPbdET5ez2hr6MezACNcBGAsYHQ/s120/nier.png",
	colorBg: "#c8bfb4"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-XxNWgrTSqPk/YWq0niOzTEI/AAAAAAAAyT8/jUVj-I70IrQgjlEFV4pHqN0rCyQ3zruRQCNcBGAsYHQ/s120/girl-cute.png",
	colorBg: "#d2c5b4"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-BsYrNzPTQLY/YWqyIbcFMcI/AAAAAAAAyTs/LENA6VVwbfMP_422S89Q23wPCuM9rC7AQCNcBGAsYHQ/s120/shinoa-hiragi.png",
	colorBg: "#8f7fa3"
}, {
	imgAnime: "https://1.bp.blogspot.com/-QXV5Ljdipoc/YTNFhItQ9pI/AAAAAAAAw-k/jcocxjXBO1U2Z4_MD9BG7O3CrptVNGXwQCNcBGAsYHQ/s120/guren.png",
	colorBg: "#6c809e"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-FMC6GSvLBmY/YWlxBumtDXI/AAAAAAAAyQE/1J0-P_onScAkfhpHN_xr2rSvHzB7fHEwACNcBGAsYHQ/s120/reika-aoki.png",
	colorBg: "#4291e9"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-tK2aQgRb7Mo/YWlwVS7F84I/AAAAAAAAyP8/NPqsOMp2uoIWpXnjhdWWBAh-FRkbIFeAwCNcBGAsYHQ/s120/nao-midorikawa.png",
	colorBg: "#7cd252"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-tvzZZibv-cU/YWlvxbcn5gI/AAAAAAAAyP0/nUHefZV4MyQ3x61EwP8JnKYFrdTNGvO3ACNcBGAsYHQ/s120/yayoi-kise.png",
	colorBg: "#fbd85e"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-2HQo-cO4bSI/YWlvYHUbOnI/AAAAAAAAyPs/d79C2L_HPNcG6R0ldwGaPR5f9HxlpNUFwCNcBGAsYHQ/s120/akane-hino.png",
	colorBg: "#eca748"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-uFFq-8ww_6w/YWlu5UipyqI/AAAAAAAAyPk/EPSsfihdiSgHYMsdX5ZZdQ3_nd0OwUaKgCNcBGAsYHQ/s120/miyuki-hoshizora.png",
	colorBg: "#f6abd0"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-qmuDHx_noW0/YWltX8Yz1vI/AAAAAAAAyPU/PYkWUy2x8XYSdGLcwvfXBsugjTpvWoGHwCNcBGAsYHQ/s120/amatsuka.png",
	colorBg: "#f28258"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-9lml-2xmGlE/YWlsiNxKMtI/AAAAAAAAyPM/WgoIWHmAUCUrMBPuwmURkBlVNk_1KySjQCNcBGAsYHQ/s120/totoro.png",
	colorBg: "#c5b388"
},  {
	imgAnime: "https://lh3.googleusercontent.com/-KyWl4kL1M5k/YWWa_GChUKI/AAAAAAAAyKg/sE5FzKDsi2s7SvpjAbjI3cVB4QgbBpx6wCNcBGAsYHQ/s120/naofumi.png",
	colorBg: "#64d252"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-Ktt14IGWvTM/YWWXsMK3hII/AAAAAAAAyKY/T5xXvLxSy2gpHQvyJL4XU3qUMPG1nRBwQCNcBGAsYHQ/s120/yuma-kuga.png",
	colorBg: "#e63030"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-8qn-fX90utg/YWWWebTZIzI/AAAAAAAAyKQ/Dk9CZeMRmCsh3scD9T6HOIO3LcVJkQ2awCNcBGAsYHQ/s120/queen.png",
	colorBg: "#b378e6"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-ufx7N8Uj-k4/YWWVmPYxBOI/AAAAAAAAyKE/_dS5s4BsbncLR9mER5cDeSKGSWDkuvKdwCNcBGAsYHQ/s120/ilulu.png",
	colorBg: "#d781c2"
}, {
	imgAnime: "https://1.bp.blogspot.com/-pZ9KtoMLkiY/YUxhvlR0KBI/AAAAAAAAxig/h1DcX4FNIr84-QJZm61dkY1t_B2xE4Z9ACNcBGAsYHQ/s120/tohru.png",
	colorBg: "#ffc560"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-zPZpwwfSlZk/YWWUI5RrxDI/AAAAAAAAyJw/ymc7QCnu4g8_tNMdA1DmazWzXGJLGHAvgCNcBGAsYHQ/s120/all-might.png",
	colorBg: "#50a5af"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-4Ad0V7NuKeQ/YV8IKs4LuVI/AAAAAAAAyAU/B-9wW5ivAwgajLVJT2LNHBRdtke3ppzIQCNcBGAsYHQ/s120/free-de-la-hoya.png",
	colorBg: "#efc122"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-yB4Uur-iry8/YV8Hx3UBbrI/AAAAAAAAyAM/7XNFGqG3WsMBvXeoyn5MrKLqqZzuH3G-wCNcBGAsYHQ/s120/yuuko-kanoe.png",
	colorBg: "#b91c1c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-QySgGHQhIoI/YROZ-v4_rlI/AAAAAAAAwGU/jRJEmaRhtDMh9SgFeq27R0dL6BJyXUA5ACNcBGAsYHQ/s120/rem.png",
	colorBg: "#52a1ff"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-AdJVHNBCeY0/YV7fz6kEfhI/AAAAAAAAyAE/BU3yFhy3jtc5gtcxFQzWAn823YUkLwH-ACNcBGAsYHQ/s120/ram.png",
	colorBg: "#f18695"
}, {
	imgAnime: "https://1.bp.blogspot.com/-rU5kOWEtTMc/YQzvR0DHARI/AAAAAAAAv7U/kTMGmdciDoEWji2CvCc7XPNnli7TcZPLgCNcBGAsYHQ/s120/satoru-gojo.png",
	colorBg: "#5e4c7c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-iCpLylmNJf4/YSyq5Gj06iI/AAAAAAAAw1U/2iRtPrlXKJ4ywgQBKC7rju10YSx29wdbQCNcBGAsYHQ/s120/sukuna.png",
	colorBg: "#c66163"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-aGVPqCuymv8/YV7fOnSV2_I/AAAAAAAAx_8/J_KLZwn7o_IV0lSEbgGev1pjPoRbW41oQCNcBGAsYHQ/s120/itadori-yuji.png",
	colorBg: "#df5059"
}, {
	imgAnime: "https://1.bp.blogspot.com/-EpyBcYLhm1c/YSC9b3DD6xI/AAAAAAAAwiE/T9K2qkwu8FI8ZO6eYSjMQfxXybzY-znfwCNcBGAsYHQ/s120/megumi.png",
	colorBg: "#778aa4"
}, {
	imgAnime: "https://1.bp.blogspot.com/-OTOSiz2rU-4/YSITiEffGbI/AAAAAAAAwiY/Rb_HPPC3xQMe0XoXHAD7ghgMrF3GIvbrgCNcBGAsYHQ/s120/toge-inumaki.png",
	colorBg: "#5d6595"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-yiT6uj1p6s8/YV7eN5ql7bI/AAAAAAAAx_w/1LIQA0Et4McKKssuYYK8EjIJB9ASR8p7wCNcBGAsYHQ/s120/rushia.png",
	colorBg: "#17bbb9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-I0B9qJf-T7A/YV0djeom50I/AAAAAAAAx9I/Rnksmr7a_7ALbs5c2o-HDy5fBLlq7DkOACNcBGAsYHQ/s120/yukinoshita.png",
	colorBg: "#338edb"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Ah4N3TCONFA/YVuvdPoep1I/AAAAAAAAx6c/EAbQA_uOQgoqrh0RRogSYc3nVS1auxi-wCNcBGAsYHQ/s120/nora-noragami.png",
	colorBg: "#ce2f24"
}, {
	imgAnime: "https://1.bp.blogspot.com/-r57R00RTL98/YVr5Ly1PFQI/AAAAAAAAx4o/9jdJI3Ns7hAI15-s2M_RIIIOfr_VRkXOQCNcBGAsYHQ/s120/juliet-persia.png",
	colorBg: "#47a3e9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-tmatNR431Ks/YVr4MwCJy8I/AAAAAAAAx4Y/L11yu_YT4LcQwW4MwDEE3qSBe5n0YwVBwCNcBGAsYHQ/s120/ichigo.png",
	colorBg: "#f7922f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-8TyO888pCcc/YVm7CXdxCsI/AAAAAAAAx18/LbDLgEdI-n8D2lpfmGozj-SoyczciU_FwCNcBGAsYHQ/s120/amelia-watson.png",
	colorBg: "#ed926e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-TjUyB_oxlOk/YVm6nH7Ge_I/AAAAAAAAx10/mUtLkDQoIPUh0gZ1MNfexbsGdSLQICPaQCNcBGAsYHQ/s120/kambe-daisuke.png",
	colorBg: "#ac4639"
}, {
	imgAnime: "https://1.bp.blogspot.com/-OD08PQusqBI/YVm4iP0V2HI/AAAAAAAAx1k/WsSLdANhJvIiF5tjitdnEvsLmHnTXMWYQCNcBGAsYHQ/s120/dr-stone.png",
	colorBg: "#30b05d"
}, {
	imgAnime: "https://1.bp.blogspot.com/-I-FXWNPoFAE/YVm3i3AXFHI/AAAAAAAAx1c/f06VS2jnvp0Pu8nzB6E1naVNBlsAYKCCwCNcBGAsYHQ/s120/tomie.png",
	colorBg: "#5e4fd0"
}, {
	imgAnime: "https://1.bp.blogspot.com/-o6w9YNzqcUQ/YVWov8uaxEI/AAAAAAAAxu8/klOSH--FH9IlUd_xH5ECLSOrpgPHaoxbgCNcBGAsYHQ/s120/roxy.png",
	colorBg: "#5173f2"
}, {
	imgAnime: "https://1.bp.blogspot.com/-sMDwtCA0j8w/YVWmlO7KkXI/AAAAAAAAxu0/K2lcwt_3PRECDmF8dtjcThGnAX-ApuXQACNcBGAsYHQ/s120/sylphy.png",
	colorBg: "#9ed463"
}, {
	imgAnime: "https://1.bp.blogspot.com/-4UJxM-_LTJU/YVWl4q67lAI/AAAAAAAAxus/USaovth6454LcqYu91P0XNxuH8DtFGHlACNcBGAsYHQ/s120/eris.png",
	colorBg: "#da3b45"
}, {
	imgAnime: "https://1.bp.blogspot.com/-3W9_NlCIWYc/YVWrtuvZlII/AAAAAAAAxvY/BnzvILd6XAAK2y1nFG_a5jVojCSMpce_QCNcBGAsYHQ/s120/shirogane-noel.png",
	colorBg: "#7ccc5a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ty5nx2ulC-Q/YVWkQiI5JWI/AAAAAAAAxuc/MAuUbGDTKP8pGoowZ4ZkSEIVvXkwKSNtwCNcBGAsYHQ/s120/shichimiya.png",
	colorBg: "#f8879e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-aUwKF3nuIVw/YVWjmIyZNcI/AAAAAAAAxuU/l1okySWBpyw_aXGldHuft3NOq8nkdGHhACNcBGAsYHQ/s120/shuna.png",
	colorBg: "#e03f70"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Bgvdzwyxx_s/YVWjLrcY_5I/AAAAAAAAxuM/ZHi1cTOwAl0RQ9hnxECBck12u3zTaJ5uwCNcBGAsYHQ/s120/chloe-aubert.png",
	colorBg: "#48a1ec"
}, {
	imgAnime: "https://1.bp.blogspot.com/-zM-vd4FsJyY/YVWg7a7Og6I/AAAAAAAAxuE/_SAM8yY7F3wTLKf109XH9R_WYTOXHwE3gCNcBGAsYHQ/s120/nasa.png",
	colorBg: "#48cbb7"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Q-8Qldx8NYY/YVWgb4vAawI/AAAAAAAAxt8/KNLaJXNOHjcLO7_YIlrrmUluR8H25_40wCNcBGAsYHQ/s120/misono-alicein.png",
	colorBg: "#791da0"
}, {
	imgAnime: "https://1.bp.blogspot.com/-y__S9GZrqLI/YVRlv9P0WOI/AAAAAAAAxrk/p68zYJLEsYQhzDNao5qSwlwJDQKRGwbwwCNcBGAsYHQ/s120/power.png",
	colorBg: "#d33838"
}, {
	imgAnime: "https://1.bp.blogspot.com/-DbOyClHe6Kk/YVRk4DLX8fI/AAAAAAAAxrc/w6IqvK2s1dQSz7WJSravOu7FtzDB3RH-QCNcBGAsYHQ/s120/uesugi-fuutarou.png",
	colorBg: "#547ac7"
}, {
	imgAnime: "https://1.bp.blogspot.com/-uG9Jg4g2trk/YVLhIybelnI/AAAAAAAAxqI/9oD6fQM2tH0nsmh3IHC8HL2SQ_tsqYnTwCNcBGAsYHQ/s120/shiki.png",
	colorBg: "#d92d25"
}, {
	imgAnime: "https://1.bp.blogspot.com/-kEFP8gx1MGA/YU7ZVnh6rdI/AAAAAAAAxnU/GVkk7lDh0Ss8VrdrjWmeEAMFsbQ0BmmFwCNcBGAsYHQ/s120/subaru.png",
	colorBg: "#ff9e2e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-PPNNc9mqMDE/YU6pfGX-_qI/AAAAAAAAxnE/uTlBZ6Exg3wLdP_XpdgWIGiMOOoBhNTeQCNcBGAsYHQ/s120/tsukasa.png",
	colorBg: "#924bfd"
}, {
	imgAnime: "https://1.bp.blogspot.com/-5Ig6hvtKe78/YRkYYc6aazI/AAAAAAAAwXA/FnfIxmakY0gDaj2ZQNKagJB3FcOv9k1wwCNcBGAsYHQ/s120/yuzaki-masa.png",
	colorBg: "#72b1a9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-VrjL5ENpGOA/YSYygPaJ8OI/AAAAAAAAwqU/wV_PIJdICOkS2rRNUhIEDsRtU7FtVHDpwCNcBGAsYHQ/s120/hanako.png",
	colorBg: "#845c5c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-urdU6IbNqQk/YUxeB70TiZI/AAAAAAAAxiI/2paKVfAeQbg8Yv3-UamgL5sUnd2CBJgBQCNcBGAsYHQ/s120/chika.png",
	colorBg: "#ef6f89"
}, {
	imgAnime: "https://1.bp.blogspot.com/-D6__O-_msvQ/YUxcfZbNRUI/AAAAAAAAxhw/KUzvixoS9xAU6a0FIvCsK9oLAbr7NL5_gCNcBGAsYHQ/s120/laika.png",
	colorBg: "#e73441"
}, {
	imgAnime: "https://1.bp.blogspot.com/-w9EzCw6GH9I/YUXPAfgxqOI/AAAAAAAAxWc/PJT2hm8IyA01FnFFZag6JJuuWtt6yqVUACNcBGAsYHQ/s120/azusa.png",
	colorBg: "#346cfd"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Q_yGYoSMsCc/YUXMtIXvcFI/AAAAAAAAxWU/0_h6bxmDOmAQTE3NoJ7j3tm-3bXhFF7oQCNcBGAsYHQ/s120/chuuya.png",
	colorBg: "#d43f54"
}, {
	imgAnime: "https://1.bp.blogspot.com/-fXXY-ggAV_Q/YUSN_1LI1hI/AAAAAAAAxUw/HX33ePuhwz8JdSL-UlBHGFrhMIZRAUElgCNcBGAsYHQ/s120/sawada.png",
	colorBg: "#f24917"
}, {
	imgAnime: "https://1.bp.blogspot.com/-CBfzspJFPxY/YUAs9uqljzI/AAAAAAAAxMQ/qoAOzMTr9XUDUAHUjPBz6q1uabv75FBMgCNcBGAsYHQ/s120/ouro-kronii.png",
	colorBg: "#319be1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-w_c4wBtKi9Y/YT8Y3an8e_I/AAAAAAAAxKI/Up1LW8u3WRsOX8tYeNArmDS_PBShaeLrgCNcBGAsYHQ/s120/nao-tomori.png",
	colorBg: "#d6425d"
}, {
	imgAnime: "https://1.bp.blogspot.com/-6lzw-haSWbM/YUAqxjCb1lI/AAAAAAAAxMI/4A1wKOq_hRQUCUmDMrHI_nHcz3YVBdg5ACNcBGAsYHQ/s120/nanashi-mumei.png",
	colorBg: "#1bbbc5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-s66DdpDJ18c/YTzAtaiYLPI/AAAAAAAAxHQ/tyD5SZWONH47Yi-CuEOtRexdYnoT-SEHwCNcBGAsYHQ/s120/siesta.png",
	colorBg: "#5d8db5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Sadys_4ngkc/YToCQp02P8I/AAAAAAAAxFQ/U6OqMDxYg6gajZ5qAQwHVYKHOJOkVCWNwCNcBGAsYHQ/s120/yui-hirasawa.png",
	colorBg: "#f3af5f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-xIvG-KQgHCw/YToBoIZJcpI/AAAAAAAAxFI/YepdsB44eT4PiQ56L9UP3ASZWtYcIDJ5ACNcBGAsYHQ/s120/suguha.png",
	colorBg: "#71b2b1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-SvqAQE5aKVA/YTn_UlWetaI/AAAAAAAAxE4/4s9BtFjUmGMrkicA5PsNuiHQKjL0Nee9QCNcBGAsYHQ/s120/flatorte.png",
	colorBg: "#6f39e1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-QsHU3ZtaYyQ/YTn1VsKAPhI/AAAAAAAAxDo/zmBFbRSCT8MgSqvGQMkRHBKTYFWVeCLsgCNcBGAsYHQ/s120/howl.png",
	colorBg: "#5b73a5"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-_RWdzsBS3SE/YXakn14EkjI/AAAAAAAAyoY/9yoekeLhNAceLCCAFlSxDvSh3I3J-DuxQCNcBGAsYHQ/s120/shophie.png",
	colorBg: "#5492b9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-x64VmYubxkQ/YROJ3n7BzfI/AAAAAAAAwF8/NSvGfJCRg7kSs9KTHWob_X7mcZDRq7eTgCNcBGAsYHQ/s120/natsu.png",
	colorBg: "#b63232"
}, {
	imgAnime: "https://1.bp.blogspot.com/-xEp-d8mWSbE/YRSzW79ql7I/AAAAAAAAwJw/khwKicWerJg9j8Pl-pRdo9i9ypqjRxLJQCNcBGAsYHQ/s120/lucy.png",
	colorBg: "#6a8eb5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Q5nY9DyKTvY/YTNXAxlfWVI/AAAAAAAAw-8/FVmZ4HfnJg0Q-s3YRHSJJiCU3UZ-gawHgCNcBGAsYHQ/s120/happy.png",
	colorBg: "#53bfde"
}, {
	imgAnime: "https://1.bp.blogspot.com/-b4Vvz5sOGUU/YRYcGy1KHjI/AAAAAAAAwNY/YJRpR4wKhkcitKkNgujy5CP3YcoCQRFagCNcBGAsYHQ/s120/gray.png",
	colorBg: "#1d3c75"
}, {
	imgAnime: "https://1.bp.blogspot.com/-mOiFncQOUVs/YTn58vMInpI/AAAAAAAAxEQ/E257xewFIGIMOojxiq1Bey1KA7f6w3GMwCNcBGAsYHQ/s120/juvia.png",
	colorBg: "#5383be"
}, {
	imgAnime: "https://1.bp.blogspot.com/-YUFt_SdYvy8/YTNWkp-D9FI/AAAAAAAAw-0/6haBP35Vz9o6p_noG8W-Fh_cUp4CsOqBQCNcBGAsYHQ/s120/erza.png",
	colorBg: "#c94c53"
}, {
	imgAnime: "https://1.bp.blogspot.com/-rV8kVW1MZa4/YRSyrw-q-nI/AAAAAAAAwJo/RGsTNcuBB6ckmKTObfibsITvjJplmhNtgCNcBGAsYHQ/s120/mirajane.png",
	colorBg: "#947a96"
}, {
	imgAnime: "https://1.bp.blogspot.com/-2HCAPw0QUHY/YRTiJ0XJKiI/AAAAAAAAwMA/P7rOKf-_nV05OO78bonVxx3-R8_qMsoRACNcBGAsYHQ/s120/zeref.png",
	colorBg: "#55606e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-5lNDQBm7iew/YTNZBW-NIdI/AAAAAAAAw_E/8ASnzMlQPBY4fZ4X0LqX6n35FbaGDTgxQCNcBGAsYHQ/s120/jellal.png",
	colorBg: "#539cf8"
}, {
	imgAnime: "https://1.bp.blogspot.com/-lQR__MBCZ5k/YTYryQi_cEI/AAAAAAAAxBA/ANDd70haeSoy6sGd6ntPoM89VCJd2zftwCNcBGAsYHQ/s120/mystogan.png",
	colorBg: "#1c3b45"
}, {
	imgAnime: "https://1.bp.blogspot.com/-yRtYb7nBr0E/YRzBU_gLV0I/AAAAAAAAwbU/X_sonF3H2lQTrlZy1BV7ilBcQpi8frlBgCNcBGAsYHQ/s120/laxus.png",
	colorBg: "#6d517e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-8jfe3JftYGw/YRYaU1AueWI/AAAAAAAAwNI/tVAV0Z5icOc80dc5zoyRMw2Axj3_EErfgCNcBGAsYHQ/s120/sting-eucliffe.png",
	colorBg: "#4d709b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-H-K_wN9MNy8/YRYbdrUgw4I/AAAAAAAAwNQ/-7tDa6sAISEJlbIz84yKQbSPJZUbbNWcgCNcBGAsYHQ/s120/wendy.png",
	colorBg: "#7183aa"
}, {
	imgAnime: "https://1.bp.blogspot.com/-XFm0T_rHQ9M/YTNVSQla_UI/AAAAAAAAw-s/BbxBKQzMzocoH4HXlJOvmFCAh1ZUHyF7wCNcBGAsYHQ/s120/gajeel.png",
	colorBg: "#646a74"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Iv9_hcPrTM8/YTn4pivVU9I/AAAAAAAAxEI/xIejdKLe8m8_kKEbwu6RoU9fBJR-iszdQCNcBGAsYHQ/s120/lyon.png",
	colorBg: "#388cda"
}, {
	imgAnime: "https://1.bp.blogspot.com/-QZ_azKpyNRk/YTn4GtSVCRI/AAAAAAAAxEA/Mv0b2DBGlQMH5jNT_OSBHzijGmwhUZTYACNcBGAsYHQ/s120/sherry.png",
	colorBg: "#eb83c1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-CvaFLBWhq-Y/YSy0IvPgscI/AAAAAAAAw10/znUl_mS771MvoPx1keo3DTe-zhSb_U6DQCNcBGAsYHQ/s120/brandish.png",
	colorBg: "#93c972"
}, {
	imgAnime: "https://1.bp.blogspot.com/-hlXBKoilBWk/YTYs7BfU1SI/AAAAAAAAxBI/PocXO2ZkZ4gXqGP28gmLm0fAD2h6_M_EQCNcBGAsYHQ/s120/shiori-asagiri.png",
	colorBg: "#6677a6"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Ue9JgZFiDa0/YTDEDdvksAI/AAAAAAAAw7A/7NK_0YhtWHY799sYCFcY0hLXbHkB-KpjQCNcBGAsYHQ/s120/yato.png",
	colorBg: "#505061"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ttJapMwcp0Y/YTDDQeQ8J-I/AAAAAAAAw64/a4HG6G-N7u0fkSyewCRZdwu2gXAQvv-5QCNcBGAsYHQ/s120/yuu-otosaka.png",
	colorBg: "#87635f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-plAW9pJE7kI/YS9_tSaSSUI/AAAAAAAAw5Q/rBQfyflYa4Ya8EZ3q4d5gnTPvssBRvINwCNcBGAsYHQ/s120/mizuhara-chizuru.png",
	colorBg: "#ec8aa1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-RTZ_8x1kYXE/YS-AMYCLT3I/AAAAAAAAw5Y/cnWceiPiQBES7naVwkIjlQG0hksM4bwkgCNcBGAsYHQ/s120/nanami-mami.png",
	colorBg: "#e9cf75"
}, {
	imgAnime: "https://1.bp.blogspot.com/-iWYzgznYZqs/YS-A-eFMChI/AAAAAAAAw5g/fUSVNmVZjiMeeAfhr6-TEt7QUB8oQ_aewCNcBGAsYHQ/s120/sarashina-ruka.png",
	colorBg: "#72a6ca"
}, {
	imgAnime: "https://1.bp.blogspot.com/-QCD0kGdPosc/YS-BnMFyFII/AAAAAAAAw5o/7vvomvfqgCsKqNYmN2CHtGQm83aSEW5ZQCNcBGAsYHQ/s120/sakurasawa-sumi.png",
	colorBg: "#eb95ab"
}, {
	imgAnime: "https://1.bp.blogspot.com/-9x-5Z7CEsag/YRd9DWpiJ-I/AAAAAAAAwRY/DNlMLG12fPAmeeZKLXMcy_O6jb7XT_-nACNcBGAsYHQ/s120/kaneki-ken.png",
	colorBg: "#b22a2a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-9WD9n1tXeSE/YS99QxqIITI/AAAAAAAAw44/0c2LNr0d5Mon0RqhLrLCueo47CPNDdMdACNcBGAsYHQ/s120/juuzou.png",
	colorBg: "#c43432"
}, {
	imgAnime: "https://1.bp.blogspot.com/-uCAwvdz8eNQ/YS82B8WTHWI/AAAAAAAAw3o/U9-pyn0DGkMFFJ-2GODNLF6ZJPH1_P7wgCNcBGAsYHQ/s120/yamauchi-sakura.png",
	colorBg: "#64608a"
}, {
	imgAnime: "https://1.bp.blogspot.com/--DiPxjdwnEE/YS81XhnQJfI/AAAAAAAAw3g/GRCKPTOL8qoRSbuxXl2jTPZeLbMv5q9OwCNcBGAsYHQ/s120/emilia.png",
	colorBg: "#a372c2"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ik-NMUqZN5E/YTDBxYkkiUI/AAAAAAAAw6w/siHXmOdbIsQVhCffF1YJV3bC1WQzLQ9DgCNcBGAsYHQ/s120/raiden-mei-herrscher.png",
	colorBg: "#d22a3c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-4tv2czpE4Vk/YS80Vh42nOI/AAAAAAAAw3Y/yRmuTPlHnG0NOh5gHWHHPziKGYyvUpHYgCNcBGAsYHQ/s120/raiden-mei.png",
	colorBg: "#5c74ce"
},  {
	imgAnime: "https://1.bp.blogspot.com/-UtholY3Us_8/YSy1KRNnLmI/AAAAAAAAw18/lMGQRiVbXrsOiJzZszNJCwsYiwrjwiB0QCNcBGAsYHQ/s120/runa.png",
	colorBg: "#ee8c6f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-2iBSFx4nMNI/YSys1xzxl8I/AAAAAAAAw1s/_Th7BUaRnnEmD1AgDLD7wVZ22E0fvLSxgCNcBGAsYHQ/s120/gintoki.png",
	colorBg: "#6984b7"
}, {
	imgAnime: "https://1.bp.blogspot.com/-NgD81tLgq84/YSyrizMSJEI/AAAAAAAAw1c/lNH0mV-av2EfvNOG_-DxdJiGCDeRDM7rwCNcBGAsYHQ/s120/raphtalia.png",
	colorBg: "#d58390"
}, {
	imgAnime: "https://1.bp.blogspot.com/-IF9ZetPgBCY/YSo3XDvvUvI/AAAAAAAAwzA/0y9SNdrheFUVh78YDcaqR3WS1EWxDm7eACNcBGAsYHQ/s120/nanami.png",
	colorBg: "#5997a5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-3N8lN_gj3BM/YSo2wYR67eI/AAAAAAAAwy4/KSjXnRZmytgBWkmFyq_kWCaJQaAZp2xXQCNcBGAsYHQ/s120/ai-ohto.png",
	colorBg: "#498ce0"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZSzzVvN8LdE/YTTK0JnysPI/AAAAAAAAw_0/m3gGnoZgOegCweAZwUijAYlKgmZxge5HwCNcBGAsYHQ/s120/diluc-ragnvindr.png",
	colorBg: "#b62918"
}, {
	imgAnime: "https://1.bp.blogspot.com/-RxXzx0Ew38g/YV0clvALGyI/AAAAAAAAx84/TftYTxSoGboBGHaccIedK9peMeTHmH9dACNcBGAsYHQ/s120/razor.png",
	colorBg: "#b0b453"
}, {
	imgAnime: "https://1.bp.blogspot.com/-YBvsNmNVSQ4/YV0dCtVo8pI/AAAAAAAAx9A/pvNyY_33vPkiak5uPYjPoAV_YXP7EMyYACNcBGAsYHQ/s120/bennet.png",
	colorBg: "#3cc725"
}, {
	imgAnime: "https://1.bp.blogspot.com/-CfaXVswhFlc/YSo0_ftKbAI/AAAAAAAAwyg/m2ARw0bvWPsZxBQs1vZfpiJQN_Ozk__3wCNcBGAsYHQ/s120/mona.png",
	colorBg: "#7d58de"
}, {
	imgAnime: "https://1.bp.blogspot.com/-pnwnO8r0uE4/YVLKCMcSKiI/AAAAAAAAxqA/e4DXLjWJCcUVhN4Ss0MbxHmGu2LHHAVKwCNcBGAsYHQ/s120/sayu.png",
	colorBg: "#ff9e2e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-G6rTPk2phXY/YT8Zas6j9ZI/AAAAAAAAxKU/M9cDoVJ_F9A6nr3ieUxVksObM9veHGVEwCNcBGAsYHQ/s120/venti.png",
	colorBg: "#179a6a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZfOx36tTjoM/YTy--HCCuuI/AAAAAAAAxHI/oZiNtUdVIMMDvrh8K-GLv2Tc1It8PdTHACNcBGAsYHQ/s120/hu-tao.png",
	colorBg: "#e44335"
}, {
	imgAnime: "https://1.bp.blogspot.com/-MhWeQZgDeGM/YSoz6-Yz1ZI/AAAAAAAAwyY/DU6rO-GCSWAiGsg6R7GqKiGZKQ1TlvRfgCNcBGAsYHQ/s120/lisa.png",
	colorBg: "#86679a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-MpM8vuBW4Fo/YSozXoRRFAI/AAAAAAAAwyQ/Y3BHq5j4ydMEuTAz_if12ugcagnppIbMACNcBGAsYHQ/s120/keqing.png",
	colorBg: "#6a4e90"
}, {
	imgAnime: "https://1.bp.blogspot.com/-VtRHcjXGE-I/YSowpsaQU9I/AAAAAAAAwyI/cOF78vqrev4ZP3czG9s4WI-6_vdfQ30hgCNcBGAsYHQ/s120/fischl.png",
	colorBg: "#59a1c9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-CWPuDY1sHy8/YSov6KDnnsI/AAAAAAAAwyA/oONr2f3b7EA3qp-ouuPYl9iCmvSFUMDQACNcBGAsYHQ/s120/jean.png",
	colorBg: "#8669aa"
}, {
	imgAnime: "https://1.bp.blogspot.com/-xPIn5BVtsJo/YSovHVFrcNI/AAAAAAAAwx4/w7qKslSrWCsrc5wE12BuIVarAiBOpIypgCNcBGAsYHQ/s120/ganyu.png",
	colorBg: "#5f8bb6"
}, {
	imgAnime: "https://1.bp.blogspot.com/-aD3BWx3PX4o/YSSzzwhT81I/AAAAAAAAwoM/MC9BwyJ7JJUgWRS2Ltxj7sWzcs26XDlxgCNcBGAsYHQ/s120/raiden-shogun.png",
	colorBg: "#795dd1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-jpzot7a6g2Y/YSIbEDq8MwI/AAAAAAAAwjQ/0nfGzDI8_-w1cXTZ1Yhn7rHQPHXUzXkDACNcBGAsYHQ/s120/qiqi-trinh.png",
	colorBg: "#8681ac"
}, {
	imgAnime: "https://1.bp.blogspot.com/-R8PRV2YKFaY/YSIXLIHI8FI/AAAAAAAAwi4/Yz6WOatmQD0tEAKSo1fslMzXPSPZbKJ9gCNcBGAsYHQ/s120/ayaka.png",
	colorBg: "#829fbc"
}, {
	imgAnime: "https://1.bp.blogspot.com/-d3zb2yEzwc0/YSYzeBRcRfI/AAAAAAAAwqc/yLDHOVsFGwg4XNN4d0eeUVdchKqukX-swCNcBGAsYHQ/s120/killua-zoldyck.png",
	colorBg: "#596890"
}, {
	imgAnime: "https://1.bp.blogspot.com/-PyYvjL4q_pU/YSYyB9jk92I/AAAAAAAAwqM/mjr1Wg-K3gotm7IbF7ydABGSsSMTSfzAQCNcBGAsYHQ/s120/saber.png",
	colorBg: "#5a9ece"
}, {
	imgAnime: "https://1.bp.blogspot.com/-jXl6-T3ZDqU/YSIdY5NKglI/AAAAAAAAwjY/BwD8wWrB_Fk0_WfW8hNXOEFruLsULSImACNcBGAsYHQ/s120/sakura-saber.png",
	colorBg: "#6ab9be"
}, {
	imgAnime: "https://1.bp.blogspot.com/-awOrSY3Dk20/YSSuDFBK2ZI/AAAAAAAAwns/Q-HkhLVGuNATAKxOt6HYb2r5-HW5Gjf8ACNcBGAsYHQ/s120/sato-kazuma.png",
	colorBg: "#5e9794"
}, {
	imgAnime: "https://1.bp.blogspot.com/-4rKk4RKASrQ/YSSupvK-BII/AAAAAAAAwn0/nOhYCRVpX38TzyyhKSogbL8e6BPSPc3ZQCNcBGAsYHQ/s120/aqua.png",
	colorBg: "#67a3df"
}, {
	imgAnime: "https://1.bp.blogspot.com/-vOdrOLFkekI/YSSvrOuDwrI/AAAAAAAAwn8/a1izC4mSmdsI5hw1Dh3bAQJCq3Xgw5E5gCNcBGAsYHQ/s120/megumin.png",
	colorBg: "#d75151"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZfOVb2CYh-s/YSSwqu8UA5I/AAAAAAAAwoE/KMOgEPK_afQXg1szgM9XFNCF6sFoZretgCNcBGAsYHQ/s120/darkness.png",
	colorBg: "#f1c16c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-d_iAO0LUAkU/YSStM_SyPBI/AAAAAAAAwnk/IC6OnZHTWMArDcN7-8abWrCuY8OwOCubgCNcBGAsYHQ/s120/kyaru.png",
	colorBg: "#9888ae"
}, {
	imgAnime: "https://1.bp.blogspot.com/-nTgmjI5le5s/YRYfMrVob-I/AAAAAAAAwOA/JlyK9C3ckdcVs957y8L8fEjuCaxfHv9bgCNcBGAsYHQ/s120/miku.png",
	colorBg: "#70adb7"
}, {
	imgAnime: "https://1.bp.blogspot.com/-PyyVxE1fOdk/YSOYsZpnlbI/AAAAAAAAwmk/Pie_6sCIamQ07_vVQIIbTvfh8W0NYBEKwCNcBGAsYHQ/s120/shido.png",
	colorBg: "#4d5190"
}, {
	imgAnime: "https://1.bp.blogspot.com/-3LHa3SDsYa4/YRM6c2x61fI/AAAAAAAAwFo/-FRHA-xDPloZORv9DkwmI0kRjMzC_agPQCNcBGAsYHQ/s120/kurumi.png",
	colorBg: "#4d5190"
}, {
	imgAnime: "https://1.bp.blogspot.com/-YXmjYIR-yGA/YSOYCV-tiLI/AAAAAAAAwmc/Hbf1fHEUZ8UTg9einGTcUsZZ7bZrwRghACNcBGAsYHQ/s120/kaguya.png",
	colorBg: "#cf332b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-s0VbdUnhjUA/YSOXkxqAJII/AAAAAAAAwmU/hSKwGzCiqAYXxsLfAf01m9sV-CdHSOqigCNcBGAsYHQ/s120/ainz-ooal-gown.png",
	colorBg: "#9463bf"
}, {
	imgAnime: "https://1.bp.blogspot.com/-vt5-jzGiOH8/YSOWo5xH6JI/AAAAAAAAwmM/0D9lOvuInp4QEowOZmTPw8JkzJ87RFqxACNcBGAsYHQ/s120/milim.png",
	colorBg: "#dcaaa4"
},  {
	imgAnime: "https://1.bp.blogspot.com/-LJRRo4gBs7Q/YRO2VozYvyI/AAAAAAAAwGs/L-KaVFidh5IJd6JhRQgOCQ1yWlJPWl3bQCNcBGAsYHQ/s120/takemichi.png",
	colorBg: "#3ea8c6"
}, {
	imgAnime: "https://1.bp.blogspot.com/-uRWT9cFz-YM/YRO2V63jXNI/AAAAAAAAwGw/SFnxNJ_o70c9MKAL-oPXcgCz38vrMwiLACNcBGAsYHQ/s120/hina.png",
	colorBg: "#ef93a2"
},{
	imgAnime: "https://lh3.googleusercontent.com/-gc5EIlvG8-I/YYJHg9kJM8I/AAAAAAAAzKo/chVZZiQbzp4Uhh6fV3ZOOYZBYZCLb8PAwCNcBGAsYHQ/s120/naoto.png",
	colorBg: "#49a6e1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-eTuwjUKUhV0/YREhK8NVWmI/AAAAAAAAwEY/y53UXtV0nMU0eaevDg9Jby1gm1yQE0m-gCNcBGAsYHQ/s120/mikey.png",
	colorBg: "#2e2a28"
}, {
	imgAnime: "https://1.bp.blogspot.com/-v6NJ2xU97mw/YTYpHwSIm-I/AAAAAAAAxAo/IMTenQHNJoo5Z_dg672r0xAymBEpAogkACNcBGAsYHQ/s120/black-mikey.png",
	colorBg: "#b5b5b5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-KVp19_Hml0Y/YSo18XzX4VI/AAAAAAAAwyw/BBYZOdscXSoRXWbD989AzFpUPuaXIeRXQCNcBGAsYHQ/s120/emma.png",
	colorBg: "#d6ba62"
}, {
	imgAnime: "https://1.bp.blogspot.com/-rOMaglwetqw/YREhKg_tsVI/AAAAAAAAwEU/Qj5XpOlUk1IeHoOHWw8JUwn2afR1qPZIACNcBGAsYHQ/s120/draken.png",
	colorBg: "#1f242a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-4jbj8k0oAcM/YRSr5HqBM5I/AAAAAAAAwJQ/Swt100rUtk06KL8TWCcIZ92s8lTNpZ9xgCNcBGAsYHQ/s120/kisaki.png",
	colorBg: "#caab2f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-QqE2bIkcOZ4/YRFCN1Pws4I/AAAAAAAAwEk/xFgTOqAw9_EMwwO86Mb3zO0m7BPlrNfhQCNcBGAsYHQ/s120/chifuyu.png",
	colorBg: "#243231"
}, {
	imgAnime: "https://1.bp.blogspot.com/-lSPUp5eyKnM/YRSHaw7DhTI/AAAAAAAAwJE/B8P5Hkzg_OwsU2DF27uhnT3gfNrP1SQ2wCNcBGAsYHQ/s120/mitsuya.png",
	colorBg: "#51597d"
}, {
	imgAnime: "https://1.bp.blogspot.com/-6ZoqKHAqDHQ/YRY20hJoUwI/AAAAAAAAwPU/H0ubM8HXIv4RfYfttJPK_16ZKc2uGWLGACNcBGAsYHQ/s120/baji.png",
	colorBg: "#6b625b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-g9cX0xoMw0w/YReDa7UKVVI/AAAAAAAAwRg/P3wp1Jmrox8Awe-iWZoJzxuqrNq-yr4eQCNcBGAsYHQ/s120/haitani-ran.png",
	colorBg: "#d1ae59"
}, {
	imgAnime: "https://1.bp.blogspot.com/-As2l6-o5qwE/YReKZTUrISI/AAAAAAAAwR4/8zeY6TjRL8QFMMOKbcSDZMLO_wtqh1F0QCNcBGAsYHQ/s120/haitani-rindou.png",
	colorBg: "#988cb3"
}, {
	imgAnime: "https://1.bp.blogspot.com/-6ofCjMnNozU/YReFvskmATI/AAAAAAAAwRo/J1_hfHGVa4E_e1Wq1tNZx8OaSk7iXjsTACNcBGAsYHQ/s120/kawaragi-senju.png",
	colorBg: "#9099be"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-2xq0zCFTZQs/YWze1oZ5SpI/AAAAAAAAyaE/hQlanzseKqw2TKhWAYdqTA5v7eum_bpagCNcBGAsYHQ/s120/izana-kurokawa.png",
	colorBg: "#7842f2"
}, {
	imgAnime: "https://1.bp.blogspot.com/-CSUXv_6Mzyk/YReHh4rwvFI/AAAAAAAAwRw/YTY2ZPSXRHYFmL93Q1vvnAdk2rYqx_3KQCNcBGAsYHQ/s120/izana-kurokawa.png",
	colorBg: "#746db6"
}, {
	imgAnime: "https://1.bp.blogspot.com/-pQ0-vSzmK9I/YSOV-Abl-PI/AAAAAAAAwmE/-lFZ7zCBgt0gQIpaFepjW0DqtRAYO1x2QCNcBGAsYHQ/s120/kazutora.png",
	colorBg: "#d7ba61"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZYSwi6ydyko/YTDA3Vs_d2I/AAAAAAAAw6o/HRq4bpRZPRMhko7QP3wdY6fAeqE2EJL9gCNcBGAsYHQ/s120/hanma.png",
	colorBg: "#7d957d"
}, {
	imgAnime: "https://1.bp.blogspot.com/-WqP7HmI6wnY/YTNDQv-Uw2I/AAAAAAAAw-M/ule75h4G3J8cOabgr4ff5ReYTWcDEbsVQCNcBGAsYHQ/s120/inui-seishu.png",
	colorBg: "#d71e1e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-nPonIkatt88/YRzIaPpi56I/AAAAAAAAwb0/5c5OMkWZ8UIaqteplu9IsgDK9AyT9w0qACNcBGAsYHQ/s120/imaushi.png",
	colorBg: "#869592"
}, {
	imgAnime: "https://1.bp.blogspot.com/-U2CZddwTurM/YTYqjNlXYVI/AAAAAAAAxAw/NAVkQtzQvtcPh6BH9ZhUhAnUDqzGtTSHgCNcBGAsYHQ/s120/smiley.png",
	colorBg: "#f78889"
}, {
	imgAnime: "https://1.bp.blogspot.com/-jLfCUVt-ku0/YTYq0NerZWI/AAAAAAAAxA4/gVC7DcTa1moHl0fQP0WXgvTYceIdY_Y9gCNcBGAsYHQ/s120/angry.png",
	colorBg: "#58cae2"
}, {
	imgAnime: "https://1.bp.blogspot.com/-MBFCmQ98WG4/YTn7X3NJUDI/AAAAAAAAxEg/AHA618tJDA4TCLF4tQxzc0FbqPihngo3wCNcBGAsYHQ/s120/sanzu.png",
	colorBg: "#d7337d"
}, {
	imgAnime: "https://1.bp.blogspot.com/-0pXhCQQM1-4/YUxjytHAf5I/AAAAAAAAxio/K4ROor3_djo9t_vu2Ax1Gh8e4buC33wFQCNcBGAsYHQ/s120/shinichiro-sano.png",
	colorBg: "#52b8e3"
}, {
	imgAnime: "https://1.bp.blogspot.com/-VCAsuLnpafQ/YT8YaDIn8dI/AAAAAAAAxKE/siJiwF1H5VQmPGrL4SSIbUWwb3HhOVJuQCNcBGAsYHQ/s120/pachin.png",
	colorBg: "#555"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Es6Dl7cMwhw/YUAn6c5N8YI/AAAAAAAAxMA/zbxvuQwnRKMkTGOOJVTIg2lSHvrXd5dUQCNcBGAsYHQ/s120/peyan.png",
	colorBg: "#8f8457"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-Ic5ZTFfu1r4/YWqzyzcsj8I/AAAAAAAAyT0/jf66xF63UX8KoVddLkG629NvPcsKFJ9uwCNcBGAsYHQ/s120/akane-inui.png",
	colorBg: "#ccb89f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-q6amnLdL5gc/YSy2VFQmhXI/AAAAAAAAw2E/ExCR7ggPpsAaWSVbEbnxqDR8_34NFBt9wCNcBGAsYHQ/s120/koro-sensei.png",
	colorBg: "#ffca4e"
},{
	imgAnime: "https://1.bp.blogspot.com/-8qoNfyqkEO4/YSOSYaIsEMI/AAAAAAAAwlk/uTZCVrF6UjIZyQAEqmmFt4FPxoJkI3NFwCNcBGAsYHQ/s120/karma.png",
	colorBg: "#8a695c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-9yp-Meoqb3M/YRoljWoM3XI/AAAAAAAAwYU/kyqmIjGW2oMent2Bexu-X4HkAd2f9eTpACNcBGAsYHQ/s120/nagisa.png",
	colorBg: "#6e99c2"
}, {
	imgAnime: "https://1.bp.blogspot.com/-HniZtfzU0FU/YSORrle6wQI/AAAAAAAAwlc/GbvJ7jGH-gQAI0mIQ-w6iDovHyE-67i8wCNcBGAsYHQ/s120/kotori.png",
	colorBg: "#ed9595"
}, {
	imgAnime: "https://1.bp.blogspot.com/-OWoTcCKzihM/YSIak4FDQLI/AAAAAAAAwjI/_bfKY2D02IoNrz0eUMM2cF_oCZOT8K8OQCNcBGAsYHQ/s120/ruby-rose.png",
	colorBg: "#1f1c25"
}, {
	imgAnime: "https://1.bp.blogspot.com/-cajCPYtQJ8c/YSIXvi5nSMI/AAAAAAAAwjA/6J81Vc83G3wd8_JlOmRtnPqMXhsZ4CQBACNcBGAsYHQ/s120/gilgamesh.png",
	colorBg: "#829fbc"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Tn8X-VeRFDg/YSIWAH53gwI/AAAAAAAAwiw/IlI2FTaBpp4FUwdp4sFMX0RUEuST-AkvwCNcBGAsYHQ/s120/yugi.png",
	colorBg: "#47a0e5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-5nLOx_ngBhE/YSIVO-85gSI/AAAAAAAAwio/smiz82bnvxMZCyMCP7ihkaorU7FekzilACNcBGAsYHQ/s120/kaiba.png",
	colorBg: "#1987dc"
}, {
	imgAnime: "https://1.bp.blogspot.com/-F9rhPF9O8J4/YSIUQyTi76I/AAAAAAAAwig/QNLWOJHXkSA2D8uW0uujvnzPN1IgxlTyACNcBGAsYHQ/s120/rikka.png",
	colorBg: "#62bdc1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-vhdXscLwLpA/YSC8vcHGfGI/AAAAAAAAwh8/vzuq8pP8LtA7htrWe-cmRlWgeZ-X20p7ACNcBGAsYHQ/s120/mahito.png",
	colorBg: "#7d919a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-yxfc3h7Z9v8/YR8tStp7s-I/AAAAAAAAwf0/3Xdh49pfIgsEu0CiJ5klDazeP6nPS0veQCNcBGAsYHQ/s120/xiao.png",
	colorBg: "#359e9b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-PqvcS2ihiFY/YR8pNRsxRqI/AAAAAAAAwe8/cBfsAJZW5C0lPTlChR151wQLPdCVDf6jgCNcBGAsYHQ/s120/nakano-ichika.png",
	colorBg: "#81b0d1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-xBTn226-fsc/YR8pnsGniVI/AAAAAAAAwfE/g4c18MCOHiEc5k5c13wAFYbH19SbvpvUgCNcBGAsYHQ/s120/nakano-nino.png",
	colorBg: "#8d8ad5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-cE5wkzwUTYs/YR8qKOehEKI/AAAAAAAAwfM/ISqo2vslNGwub4toONQ3g23R2UxGRXwvACNcBGAsYHQ/s120/nakano-miku.png",
	colorBg: "#8d9ee0"
}, {
	imgAnime: "https://1.bp.blogspot.com/-udW1Hr18E9g/YR8qmi7gMeI/AAAAAAAAwfU/5GzcX-C1RzoMaBYh2-2gIT7xQaoPGr82ACNcBGAsYHQ/s120/nakano-yotsuba.png",
	colorBg: "#a1b369"
}, {
	imgAnime: "https://1.bp.blogspot.com/-EhXyCXjwzzQ/YR8q-yddHBI/AAAAAAAAwfc/Nwx8cfdXA5sK1tdTQnjVD65CCQuzY3ECQCNcBGAsYHQ/s120/nakano-itsuki.png",
	colorBg: "#d0797f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-iWpPbRc90DE/YR8nx58KiAI/AAAAAAAAwes/rayjadogDoA6NS0vHzCLmdJcKHRYJ8O6QCNcBGAsYHQ/s120/bakura-ryou.png",
	colorBg: "#7798ab"
}, {
	imgAnime: "https://1.bp.blogspot.com/-asAnOpdRjGY/YR8oW7OR46I/AAAAAAAAwe0/9r925vQ7QIkBSc8VOLPl_dH3YLmrUZgowCNcBGAsYHQ/s120/marik-ishtar.png",
	colorBg: "#75648c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-d0T3C-GEc_o/YR8l1cuS4VI/AAAAAAAAwec/5pwcxgbxNAEgkaM91kR7aC-AXP4bzyqkwCNcBGAsYHQ/s120/kiyotaka-ayanokÅji.png",
	colorBg: "#ae3758"
}, {
	imgAnime: "https://1.bp.blogspot.com/-9o3VfXclCjI/YR0efaJrqWI/AAAAAAAAwcs/FUYhjAFOa5UcHQpVZHdBndXVe9oDdF4owCNcBGAsYHQ/s120/inuyasha.png",
	colorBg: "#b33232"
}, {
	imgAnime: "https://1.bp.blogspot.com/-_A3LKyDXLog/YRzCk8MJ_2I/AAAAAAAAwbk/3wVF7K__WTcdbSy8hV8EQuXtKpI4c1DCACNcBGAsYHQ/s120/sistine-fibel.png",
	colorBg: "#7066a4"
}, {
	imgAnime: "https://1.bp.blogspot.com/-_t9XqCIJNsE/YRzErdOjFTI/AAAAAAAAwbs/b70p7XPMOC4C-_SNB9c7bCgi0G-WwfafgCNcBGAsYHQ/s120/syalis.png",
	colorBg: "#ae9bc9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-QA-T_TJQfwY/YRzCDJn8fAI/AAAAAAAAwbc/1QIBF53Cg2IVFpZDLOsb3WRmlecB-UhaACNcBGAsYHQ/s120/rei-ayanami.png",
	colorBg: "#8184c0"
}, {
	imgAnime: "https://1.bp.blogspot.com/-OZmIFmnVidg/YRpoBQGazSI/AAAAAAAAwZM/x6SgLYXa9TksSjMipERh0lxczqRYEHs9gCNcBGAsYHQ/s120/iruma.png",
	colorBg: "#3fafe8"
},  {
	imgAnime: "https://1.bp.blogspot.com/-vx2FmYGYDCw/YRpthu0wCqI/AAAAAAAAwZU/S4HRAYCtM4IdKP7qDsNRFxfajyx9UszNQCNcBGAsYHQ/s120/yuri.png",
	colorBg: "#967ea8"
}, {
	imgAnime: "https://1.bp.blogspot.com/-vM0G_d3lFEs/YRpm0ZKTPaI/AAAAAAAAwY8/yvxwYDQPKpMd3YK0A-pjPAs6XjhXUY4HACNcBGAsYHQ/s120/shigeo-kageyama.png",
	colorBg: "#56377a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-wJ-idSqrHqM/YRooLbjVYaI/AAAAAAAAwYs/Q1LS3_45gk84ELg9MPd_ZMiBjD3Nv-9HACNcBGAsYHQ/s120/elaina.png",
	colorBg: "#9e80af"
}, {
	imgAnime: "https://1.bp.blogspot.com/-We9e4i3lrco/YRonHbAFFyI/AAAAAAAAwYk/-qLa9GEhFRMLPg9wFnMuHB1Rylq7XwvXgCNcBGAsYHQ/s120/mirai.png",
	colorBg: "#e08e7c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-dVpmyiUWUjI/YRomRtXCTQI/AAAAAAAAwYc/KEo1d5_HVg4FruI72FaMhTMarLqwLiYuACNcBGAsYHQ/s120/umaru.png",
	colorBg: "#ee8c44"
}, {
	imgAnime: "https://1.bp.blogspot.com/-mh3l0YzysJA/YRkZNz6np5I/AAAAAAAAwXI/5_LO9atLRcghzYIhlgy2M4VNLQkEb3vdgCNcBGAsYHQ/s120/saitama.png",
	colorBg: "#e5b646"
}, {
	imgAnime: "https://1.bp.blogspot.com/-TwlUNbrROMk/YURPXWOj3GI/AAAAAAAAxUo/nBWqMpJ9GHIX4CkvddtH8zI68pKC8LaEQCNcBGAsYHQ/s120/genos.png",
	colorBg: "#f2d04a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZjrAsUTlXC0/YRka57MWz9I/AAAAAAAAwXY/-FqqIpJSl3wSmXU_r10wvYPGx-IPIXeBwCNcBGAsYHQ/s120/tatumaki.png",
	colorBg: "#1a562f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-0G8C-3jV7OA/YRkaIbWPk6I/AAAAAAAAwXQ/r7yNvt9hkn4iU0HQPhwesVULOvun_zV5gCNcBGAsYHQ/s120/fubuki.png",
	colorBg: "#44756a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-lmhjUoye2F4/YRkc5pWLuFI/AAAAAAAAwXg/SlINgvp3Fyk3NIbw_tHYpwR9FibI0Qd4gCNcBGAsYHQ/s120/tanmoshi.png",
	colorBg: "#5f88b8"
}, {
	imgAnime: "https://1.bp.blogspot.com/--fQyJVG_a8w/YQjvnVLWzVI/AAAAAAAAv0o/h0zvBsl8ui8BslbvieRhT_S-tF9pgQ8ugCNcBGAsYHQ/s120/zero-two.png",
	colorBg: "#d89194"
}, {
	imgAnime: "https://1.bp.blogspot.com/-UurSmwFQu3w/YRkDhF5a50I/AAAAAAAAwWo/GE3qZZ31Sv82R8dRYLMy3dEwnKfTeqHSQCNcBGAsYHQ/s120/ichigo.png",
	colorBg: "#76b1db"
}, {
	imgAnime: "https://1.bp.blogspot.com/-BhMRkGfKEcQ/YRkCyrujOOI/AAAAAAAAwWg/nYTTrmR57wUZKr6ekHmd_h6g4G46F7wygCNcBGAsYHQ/s120/yosano-akiko.png",
	colorBg: "#7b8ed4"
}, {
	imgAnime: "https://1.bp.blogspot.com/-qrSN7NyHQpQ/YRkCVDzuf5I/AAAAAAAAwWY/rACWWd0jBXUCF4ged36vtY5cnpk0c_WXwCNcBGAsYHQ/s120/sakura-nanamine.png",
	colorBg: "#9fb764"
}, {
	imgAnime: "https://1.bp.blogspot.com/-De8cXmbTJ5I/YRkBvmtVItI/AAAAAAAAwWQ/_1yGmv0iao8BN7VmqF7x7ljaI13P5gPEwCNcBGAsYHQ/s120/violet.png",
	colorBg: "#71a7d4"
}, {
	imgAnime: "https://1.bp.blogspot.com/-OPUv8BBx4Rk/YRkBGf-JVoI/AAAAAAAAwWI/5y6IsQSeE5gNx5WF4Y3-W_a2C7khMZ98wCNcBGAsYHQ/s120/anko.png",
	colorBg: "#71a7d4"
}, {
	imgAnime: "https://1.bp.blogspot.com/-jM6COnizSUQ/YRkARvWMdjI/AAAAAAAAwWA/udx-Gdg32Y8bEENZIV3q5CI5nOqCstFrQCNcBGAsYHQ/s120/albedo.png",
	colorBg: "#5d598f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Pkj0LEwj3sQ/YRj9OC_B_XI/AAAAAAAAwVg/avaHbvdGwPE5ZNrR9jMPbhnPoRtO_XsPQCNcBGAsYHQ/s120/izumi-sagiri.png",
	colorBg: "#4eadd0"
}, {
	imgAnime: "https://1.bp.blogspot.com/-fTYk9A3OTZA/YSOVIMv5JEI/AAAAAAAAwl8/UqhUayokibcjXGOAakuQ7rlnWzKmylVJQCNcBGAsYHQ/s120/doraemon.png",
	colorBg: "#58d3e9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-REeSAUh2TG4/YRjg_r4LpNI/AAAAAAAAwU4/PeXKDChyqUkpBxCRK9W_0ftwKJJWzEiFwCNcBGAsYHQ/s120/nobita.png",
	colorBg: "#e6b030"
}, {
	imgAnime: "https://1.bp.blogspot.com/-dN7wT3ELv9g/YRjgVJIzC0I/AAAAAAAAwUw/S2aOBPSbnL4RC19tNjZoAJteha-89OA0QCNcBGAsYHQ/s120/shizuka.png",
	colorBg: "#6d97d1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-HRuLU6P55yg/YRjb4ixaiYI/AAAAAAAAwUg/niouzSPLEHsUDOJkdohnQHLadyu3qTJWwCNcBGAsYHQ/s120/mai.png",
	colorBg: "#5872a3"
}, {
	imgAnime: "https://1.bp.blogspot.com/-zFrWvfdTVWA/YRd8gy6n7JI/AAAAAAAAwRQ/O7sSfUZqcMoV9PmDfFD8go6Qba-V9qH4wCNcBGAsYHQ/s120/hiroomi.png",
	colorBg: "#8ca5d6"
}, {
	imgAnime: "https://1.bp.blogspot.com/-55_tSYQL9ug/YRZwQ40H7II/AAAAAAAAwQo/0nkUsGCA0-Y__6xParO7rnOxVW3FrBYXgCNcBGAsYHQ/s120/kenma.png",
	colorBg: "#6ebed2"
}, {
	imgAnime: "https://1.bp.blogspot.com/-qVfZv8mCO50/YRZvx7LPx1I/AAAAAAAAwQg/tyLE5yDN1AMIBTLRKO0Gix1quHMSnbzeACNcBGAsYHQ/s120/siesta.png",
	colorBg: "#70a8e1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZwfhIt4pnWY/YRZvL_jaulI/AAAAAAAAwQY/7p74mz07p7Almsl1sS-081MBkQDM-qjSgCNcBGAsYHQ/s120/anos.png",
	colorBg: "#57668b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-6X67CRLT9xw/YRZsNC8j95I/AAAAAAAAwQI/ZoohCuuycbcHkSldFo99CDWhrgS8vDOcQCNcBGAsYHQ/s120/gin.png",
	colorBg: "#999"
}, {
	imgAnime: "https://1.bp.blogspot.com/-SRk-hyfU4Ps/YRZujEn7zdI/AAAAAAAAwQQ/Rhd03JAq2HE0tLs4IGxgfj6dkpVonKFOgCNcBGAsYHQ/s120/takegawa-hotaru.png",
	colorBg: "#82d8f0"
}, {
	imgAnime: "https://1.bp.blogspot.com/-QSjGuLAEmio/YRZrUNcSrmI/AAAAAAAAwQA/NjqD8DSbdOgefgMJlyTo33DJJvJ9_p2NQCNcBGAsYHQ/s120/shin.png",
	colorBg: "#de4646"
}, {
	imgAnime: "https://1.bp.blogspot.com/-RJRii2KuuHY/YRZquoSW9eI/AAAAAAAAwP4/DflBu4AwIaYTGNpOmfd8Y5-lyfKNwqPjACNcBGAsYHQ/s120/usagi-tsukino.png",
	colorBg: "#6fb6e8"
}, {
	imgAnime: "https://1.bp.blogspot.com/-m6oGs62c_6c/YRYuSq0_WGI/AAAAAAAAwOo/Bk8w2jJaF8I6AcDFdBM9SmUvHSamKW6-QCNcBGAsYHQ/s120/cherry.png",
	colorBg: "#c48091"
}, {
	imgAnime: "https://1.bp.blogspot.com/-fmUtM-zQM9o/YRYgO6j-0mI/AAAAAAAAwOI/Bh8niC5NzB4Jkjyk946vCQCXo3cI2l-1wCNcBGAsYHQ/s120/asta.png",
	colorBg: "#413b3b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-y47UaqW6fK8/YSyqP2EbkTI/AAAAAAAAw1M/fGu_F1QR2fsQyuuLt2aMY5KYBJZn5G6vACNcBGAsYHQ/s120/luck-voltia.png",
	colorBg: "#5997a5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Ej_wntEbcLI/YUxgnSES1jI/AAAAAAAAxiY/EjjnzqFLnz00YXjalvLW4egvRACdbT0lwCNcBGAsYHQ/s120/yuno.png",
	colorBg: "#338f44"
}, {
	imgAnime: "https://1.bp.blogspot.com/-xb561qOPUcI/YRYevHx7j-I/AAAAAAAAwN4/Y-z3NiL5rxgQA6FhdZ9JrJf0jkkfZfhCQCNcBGAsYHQ/s120/midoriya.png",
	colorBg: "#3b867a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-6mzxE4TIB84/YR8nGhqvrfI/AAAAAAAAwek/gJuIglJDvUkodcGo0KMRYgXZRXJHY74jwCNcBGAsYHQ/s120/toga-himiko.png",
	colorBg: "#cf7048"
}, {
	imgAnime: "https://1.bp.blogspot.com/-eMi-Ag6cIXY/YRTYOJOmtmI/AAAAAAAAwLQ/kLGFd3REUiUZ2uoslq5hu4HVLPjj73GBwCNcBGAsYHQ/s120/hair-black.png",
	colorBg: "#8cbcc7"
}, {
	imgAnime: "https://1.bp.blogspot.com/-xA6jdId--1E/YRTXcNLjY_I/AAAAAAAAwLI/38WXycddlDcVhZyLeTbYIeMJd9Cnl_Q3wCNcBGAsYHQ/s120/yumeko.png",
	colorBg: "#ba312b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-fWRP5oGItKc/YRTb6zxEwNI/AAAAAAAAwLg/4q6MkE2xvewTZDnl8XyzSJFL7AXyvLpuQCNcBGAsYHQ/s120/dimaria-yesta.png",
	colorBg: "#3f040c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-4eukR2D0IRo/YRTYYWOtD2I/AAAAAAAAwLU/6cztrMXEZrEQ-9M7esEtyAabylOSDGrbQCNcBGAsYHQ/s120/amajiki.png",
	colorBg: "#515480"
}, {
	imgAnime: "https://1.bp.blogspot.com/-G1IztA3Jjdk/YRTVk9_9QSI/AAAAAAAAwKw/h-qaemMIWSgMfvKPHrNw0b_65K-TiCapQCNcBGAsYHQ/s120/dazai.png",
	colorBg: "#6e7e9e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-KQK1LnPa-Bs/YSS1A2wCYkI/AAAAAAAAwoU/JuEOM_ICDXocI8AgVTV7_HRbOeKMBmnaACNcBGAsYHQ/s120/reki.png",
	colorBg: "#5a9ece"
}, {
	imgAnime: "https://1.bp.blogspot.com/-L7-4WTcl9cg/YRTVFzrKNkI/AAAAAAAAwKo/eWtiBmPstqk7BTWESJJNOsf3tGvv6g7RgCNcBGAsYHQ/s120/langa.png",
	colorBg: "#56789e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Eab8_mlJTa4/YRTUws8JxSI/AAAAAAAAwKg/12-f-bluNLc_d3Rs_eXLZuWtawW1yChKACNcBGAsYHQ/s120/dabi.png",
	colorBg: "#394972"
}, {
	imgAnime: "https://1.bp.blogspot.com/-XUThObI3ocY/YRS15lmSEVI/AAAAAAAAwKQ/cKoseU50t04u4WWs1L5A2CXt8BjyrEFKQCNcBGAsYHQ/s120/kuroko.png",
	colorBg: "#499bba"
}, {
	imgAnime: "https://1.bp.blogspot.com/-zTXgM6gOWLQ/YRSG1bplCCI/AAAAAAAAwI8/AqQu87U71QEyET8ZSosCv2vDVgws_z9qwCNcBGAsYHQ/s120/jinmori.png",
	colorBg: "#db432a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Iu_ufSRyN2A/YRSERnBX33I/AAAAAAAAwIs/-tITYLeOIH8xFHlftzu31YnaFKJBvMI_gCNcBGAsYHQ/s120/l-lawlie.png",
	colorBg: "#454545"
}, {
	imgAnime: "https://1.bp.blogspot.com/-_3PVB5nmMfU/YRTTLjnOSlI/AAAAAAAAwKY/InFTv3vobwQbbsBtvOo5cGx43ypFD54sACNcBGAsYHQ/s120/naraku.png",
	colorBg: "#9a739c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-GP8DnCIMyu4/YRSDG1i0C3I/AAAAAAAAwIk/RanzHqnT0SgYRY4N2uXm0U3gdBaivIT8QCNcBGAsYHQ/s120/sesshoumaru.png",
	colorBg: "#d93931"
}, {
	imgAnime: "https://1.bp.blogspot.com/-jq1aylAo5jo/YRTdk7VI1RI/AAAAAAAAwLw/d2sGi7FBggUMo3B9p8nHKfZxI9dgjiasACNcBGAsYHQ/s120/tomoe.png",
	colorBg: "#6d7094"
}, {
	imgAnime: "https://1.bp.blogspot.com/-GPKm4bZODgM/YRR5xF1ovKI/AAAAAAAAwIY/aDh53Q3kFksIimdSTQl-lVKcKaFLuV3sQCNcBGAsYHQ/s120/luna.png",
	colorBg: "#db98c1"
}, {
	imgAnime: "https://1.bp.blogspot.com/-FeUaudTnGfw/YRPh8v5oiaI/AAAAAAAAwHM/HCDEzHqRlT8kbTDtAX8QQw8XP2rGKk8FgCNcBGAsYHQ/s120/rimuru.png",
	colorBg: "#5d9bae"
}, {
	imgAnime: "https://1.bp.blogspot.com/-C7Z2kPSCCRU/YRR3nMkiUpI/AAAAAAAAwIE/xtcFk4AWj_IJkWTAnyO_5JHH99mHuXsDQCNcBGAsYHQ/s120/tsukishima.png",
	colorBg: "#233579"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZaAIqpupQ4o/YRSGK765q2I/AAAAAAAAwI0/GByV26sVTMsUvYvivsZMPE8dEYTSQINHQCNcBGAsYHQ/s120/hinata.png",
	colorBg: "#508cb6"
}, {
	imgAnime: "https://1.bp.blogspot.com/-W6Miadfk_GE/YRj_WxKAjmI/AAAAAAAAwV4/l0WseQgMeKQG62tC2Xyy264_H1MtLidfwCNcBGAsYHQ/s120/kageyama-tobio.png",
	colorBg: "#5b4e92"
}, {
	imgAnime: "https://1.bp.blogspot.com/-T9CkONxLm8k/YRPf5prJMFI/AAAAAAAAwG8/k_6hBBIwubEAHROMeYATMKkLaW3DKkQnwCNcBGAsYHQ/s120/tanaka.png",
	colorBg: "#da853e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-fXoRvwNdIpE/YRj-dpN1SKI/AAAAAAAAwVw/dIvo1Bcg4w8-rUbmB4qJ2ipIK2NKEWw-QCNcBGAsYHQ/s120/oikawa-tooru.png",
	colorBg: "#4a8a83"
}, {
	imgAnime: "https://1.bp.blogspot.com/-NnBymrk0IMQ/YROeO7_sOTI/AAAAAAAAwGc/ziDDpGoDW1ofzcwpVDHm8-3V5StfyTwBQCNcBGAsYHQ/s120/uzaki.png",
	colorBg: "#5b7eae"
}, {
	imgAnime: "https://1.bp.blogspot.com/-HIRiLwhw3B8/YROWkdFfBII/AAAAAAAAwGE/iqatYU8c8MQyeBKcXRrxUlsXoupTkTW0gCNcBGAsYHQ/s120/todoroki.png",
	colorBg: "#575468"
}, {
	imgAnime: "https://1.bp.blogspot.com/-WU-q3NhNHOE/YROWkUNba0I/AAAAAAAAwGI/J9nPwg-SmB8btzBAp4EbegtlzcJS1Jc3QCNcBGAsYHQ/s120/levi.png",
	colorBg: "#4b3b33"
}, {
	imgAnime: "https://1.bp.blogspot.com/-xf4xB37HTJs/YQ5DtNnzArI/AAAAAAAAv9w/4SELVV2jR4crbubus_FvU1-S997LDKcQACNcBGAsYHQ/s120/eren.png",
	colorBg: "#615852"
}, {
	imgAnime: "https://1.bp.blogspot.com/-3prj-XMYyIU/YRjcev7aneI/AAAAAAAAwUo/TWKRGM0wCgc8lregfj24XMBJmRWeRlVGgCNcBGAsYHQ/s120/mikasa.png",
	colorBg: "#8c664e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Ibdk4YOzCyM/YSouFCpdceI/AAAAAAAAwxw/VsoWXyfX1VgcMMB8O8CYYlrk1tZlG5uoACNcBGAsYHQ/s120/hanji-zoe.png",
	colorBg: "#715f51"
}, {
	imgAnime: "https://1.bp.blogspot.com/-b80EJ6JXLcE/YTND-eB200I/AAAAAAAAw-Y/pkRv43Nk0o8VvY2vqVVUw6HtQWPVVYAogCNcBGAsYHQ/s120/leonhart.png",
	colorBg: "#949586"
},  {
	imgAnime: "https://1.bp.blogspot.com/-EAkKo3u5b6g/YQ4-grJXtvI/AAAAAAAAv9I/5q99kAI5QZMcicrlhDlERmQfxdUhdBYogCNcBGAsYHQ/s120/bakugou.png",
	colorBg: "#556b71"
}, {
	imgAnime: "https://1.bp.blogspot.com/-2InVDhAxc8g/YQ_S1fnAICI/AAAAAAAAwBs/9EP8aMGV-WMHHSEcLsC5JcIogqmU7GuBQCNcBGAsYHQ/s120/sungjinwoo.png",
	colorBg: "#294c6d"
}, {
	imgAnime: "https://1.bp.blogspot.com/-8OSlLqsVzDo/YQ_TcS5mWGI/AAAAAAAAwB0/U9dpJYl4H0ki37lxPDIwgsYVVUWfHvNAgCNcBGAsYHQ/s120/tsubasa.png",
	colorBg: "#329dcf"
}, {
	imgAnime: "https://1.bp.blogspot.com/-thPxayhCJgk/YRd7iUzQ4fI/AAAAAAAAwRI/BmtK0Oskar06sr2e2ML3PPAve8XIHSvjACNcBGAsYHQ/s120/wakabayashi.png",
	colorBg: "#ec5353"
}, {
	imgAnime: "https://1.bp.blogspot.com/-6VvfjcG1Qko/YSo1biJSi_I/AAAAAAAAwyo/zvPXO7HpiCYSb9togzX3jbgRNwrZa6LNQCNcBGAsYHQ/s120/misaki-taro.png",
	colorBg: "#356fab"
}, {
	imgAnime: "https://1.bp.blogspot.com/--O_jkT24LQc/YREX0A8kAZI/AAAAAAAAwEE/8X8hJ2z6Z5A3n2-b2D_oOCkBKo_TWj4zgCNcBGAsYHQ/s120/oreki.png",
	colorBg: "#2b587e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-UckB2jBckBc/YRkEzD9LLJI/AAAAAAAAwW4/rxNah_hYNLAEwe3RhVH0m3BOQJP70i_KgCNcBGAsYHQ/s120/chitanda-eru.png",
	colorBg: "#80729a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-jb5ctGDinwo/YREd5q25CMI/AAAAAAAAwEM/q-FFPwT5r40aFjuSf-L_AZYU3BA-CJlCgCNcBGAsYHQ/s120/chaheain.png",
	colorBg: "#581f27"
}, {
	imgAnime: "https://1.bp.blogspot.com/-BmO6CxcuilM/YQ48dJgF4yI/AAAAAAAAv84/L_uHCWjHRsInbfjc4DTB5fSf_YcE61h7wCNcBGAsYHQ/s120/dio.png",
	colorBg: "#0d692b"
}, {
	imgAnime: "https://1.bp.blogspot.com/--rjVyHJG820/YQ49CZSy5tI/AAAAAAAAv9A/TS5JHmGuJ8Qg7dIR61Cz0WF34vwDAtMhgCNcBGAsYHQ/s120/jotaro.png",
	colorBg: "#53544c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-QTM0CntMMws/YVm6F8yX-NI/AAAAAAAAx1s/_8hWP_ct_4IClSrJYwRxlbB50LPWRP1rgCNcBGAsYHQ/s120/joseph-joestar.png",
	colorBg: "#30b05d"
}, {
	imgAnime: "https://1.bp.blogspot.com/-P57eNIhd9h8/YUxelO9DWXI/AAAAAAAAxiQ/aJj5LtuiJY0mfvtJ_AwTeUw7SWyJ6CBawCNcBGAsYHQ/s120/jonathan-joestar.png",
	colorBg: "#3749ce"
}, {
	imgAnime: "https://1.bp.blogspot.com/-U2BDkAqUc_0/YR8uZ96xjFI/AAAAAAAAwgE/SFkpUXX9TKw9AxIn00OnS3WbttE20V-lACNcBGAsYHQ/s120/giorno-giovanna.png",
	colorBg: "#b073a7"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-QHdmSZL8oKI/YYJF8w9MKnI/AAAAAAAAzKY/G4k6IrmXNuw2JFJv079-i7YoLly6x25-QCNcBGAsYHQ/s120/kakyoin.png",
	colorBg: "#516141"
},{
	imgAnime: "https://lh3.googleusercontent.com/-s0QTKUOv2jI/YYJLFdhkE8I/AAAAAAAAzLI/INl7D879z8sBdWjxsP45NcAP5G6wvWV6ACNcBGAsYHQ/s120/Jolyne.png",
	colorBg: "#6ba940"
},{
	imgAnime: "https://lh3.googleusercontent.com/-AuMBUWhP72M/YYJLnjpvQmI/AAAAAAAAzLQ/mzP5uor0y5AayomFxycJbS78FnjUh0nFwCNcBGAsYHQ/s120/Johnny.png",
	colorBg: "#4ea6de"
},{
	imgAnime: "https://lh3.googleusercontent.com/-L-ORMRtJ7-g/YYJMQPASj0I/AAAAAAAAzLY/k8-QVDw1sI0cpHdTiIo2pUTlTSSs-OQggCNcBGAsYHQ/s120/Josuke.png",
	colorBg: "#396cb1"
},{
	imgAnime: "https://1.bp.blogspot.com/-GUfoqwtCUMM/YQutcKmSA4I/AAAAAAAAv5g/yCR267Bt5aoJTLZ2XmapgPRKcfcGR2MUQCNcBGAsYHQ/s120/kanna.png",
	colorBg: "#eb9ead"
}, {
	imgAnime: "https://1.bp.blogspot.com/-TkK1lZHat10/YQutoQC_JLI/AAAAAAAAv5k/Eejn12Mxgl0XnZIDAD4yZF00tiPneJOzwCNcBGAsYHQ/s120/loli.png",
	colorBg: "#3aa3c5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-nDX2y2Dub6c/YTzFBBLoCiI/AAAAAAAAxHo/7GzF-Th7U6wCOYeg4lqFeI9mQ1TOktVOgCNcBGAsYHQ/s120/conan.png",
	colorBg: "#256ccd"
}, {
	imgAnime: "https://1.bp.blogspot.com/-72_sWVkpfXg/YQuqjPD3tXI/AAAAAAAAv5A/dAiMGo-9vrsMGlQzS4SAXxt2BWmi3G8NwCNcBGAsYHQ/s120/shinichi.png",
	colorBg: "#55b5ff"
}, {
	imgAnime: "https://1.bp.blogspot.com/-hZz72N2WAUA/YQuqjFY78dI/AAAAAAAAv5E/e8Yqg6WF3Bkx4YJKqImoFVHAXuFIkvcnQCNcBGAsYHQ/s120/ran.png",
	colorBg: "#8770b9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-BOUOT5544EE/YTn8rFxtVoI/AAAAAAAAxEo/tVMle4919CM7y1QMkLXoTipaHT8jzi4tACNcBGAsYHQ/s120/aoko.png",
	colorBg: "#c773b9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-qyf-8emKvK4/YToA-_s6guI/AAAAAAAAxFA/MlckVLEQwWs8fTJxBqFAQSsBYYs8P9IQwCNcBGAsYHQ/s120/sonoko.png",
	colorBg: "#4c88cb"
},{
	imgAnime: "https://lh3.googleusercontent.com/-A0XlrnUTAO0/YYJFRA9k8-I/AAAAAAAAzKQ/mKtK4rV2xnw95XMfleOXjCCRFXvLP2cnQCNcBGAsYHQ/s120/akai-shuichi.png",
	colorBg: "#805086"
},  {
	imgAnime: "https://1.bp.blogspot.com/-q9iYSou-gtY/YQurPYNR9BI/AAAAAAAAv5Q/FCP21rj34-gQJlTgTCoDPwSJo7jAJX4-QCNcBGAsYHQ/s120/kaito-kid.png",
	colorBg: "#292c35"
}, {
	imgAnime: "https://1.bp.blogspot.com/-MAUik5cHo_4/YVr5rM_B4II/AAAAAAAAx4w/5d9QD991bjwIZEAzdqbUBE3Bnw34boj5wCNcBGAsYHQ/s120/kazuha-toyama.png",
	colorBg: "#bda481"
}, {
	imgAnime: "https://1.bp.blogspot.com/-HDpEG7NoL60/YVr4sDv5-VI/AAAAAAAAx4g/Qc7AFm1tgLoI0xg1pUarbRozRvY4X_HwwCNcBGAsYHQ/s120/akako-koizumi.png",
	colorBg: "#5356be"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Nn9cqk74CRI/YQqaQFBMe9I/AAAAAAAAv3M/7Ln3AFlxpw82coa1WJMo1ASoDQ1kozkXACNcBGAsYHQ/s120/luffy.png",
	colorBg: "#f1bc1c"
}, {
	imgAnime: "https://1.bp.blogspot.com/--yQEa2GmvJ8/YQqfp2Q3e1I/AAAAAAAAv3g/LZ5odF86OMoYBrwB1pwld3msat5vY54-gCNcBGAsYHQ/s120/zoro.png",
	colorBg: "#2e483e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-d3EXXNjZcKs/YQts2JJ_CrI/AAAAAAAAv4c/OCC6qFeY_uM9oXUWEtz7YCuUzv5hudavACNcBGAsYHQ/s120/sanji.png",
	colorBg: "#484538"
}, {
	imgAnime: "https://1.bp.blogspot.com/--qyypSJcnNo/YROJGoz7PHI/AAAAAAAAwF0/3CmiNSwzUicxszMYcp0NI2xiYA7BheEEwCNcBGAsYHQ/s120/ace.png",
	colorBg: "#b63232"
}, {
	imgAnime: "https://1.bp.blogspot.com/-t3MVKT5yzfw/YRKzXAmxxjI/AAAAAAAAwFc/41B5EHD0_lIxy__IKFDykcWDBqar0nwDgCNcBGAsYHQ/s120/nico.png",
	colorBg: "#555b8f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-F7vYcascEwM/YR8t4rl992I/AAAAAAAAwf8/Moa1llXYzasPDE8tCVefKAMFoEXZgqbsQCNcBGAsYHQ/s120/doflamingo.png",
	colorBg: "#d1819f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-pnkm5m1xDJ8/YRPyW6j6VsI/AAAAAAAAwH0/wNMrb4XXVYk8KVmFCBgSe_DHcSYa3HAyQCNcBGAsYHQ/s120/nami.png",
	colorBg: "#34a6b4"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Fa4JXpOY0V8/YQ5FIa8XYGI/AAAAAAAAv94/buzlwK_chWc1BwHshCW50ijsu6juwm7ygCNcBGAsYHQ/s120/shanks.png",
	colorBg: "#474e6a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-cV_zpPy9daA/YRYhz-ntOII/AAAAAAAAwOY/7tSf4VK9DvITyqxUuhfnxr1kgrebCCubQCNcBGAsYHQ/s120/trafalgar-law.png",
	colorBg: "#efb23e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-bFakwCTGtc8/YUAnJGoMLpI/AAAAAAAAxL4/CCgVlgFdvAA39_wz8eV64lXnapUbBWpqwCNcBGAsYHQ/s120/marco.png",
	colorBg: "#bd3eb9"
}, {
	imgAnime: "https://1.bp.blogspot.com/-XBr4TvyyrQ8/YTy9zUwImqI/AAAAAAAAxHA/By3sKe8GXWY6wPegXq7tbmBFG5RxYngdwCNcBGAsYHQ/s120/katakuri.png",
	colorBg: "#e63e77"
},{
	imgAnime: "https://lh3.googleusercontent.com/-06C5QjXT_WI/YXpg6a_QnVI/AAAAAAAAy8g/YCqQWPEnH9QNZP_AwE7GCqHIuY29i3vlQCNcBGAsYHQ/s120/sabo.png",
	colorBg: "#429ddc"
},{
	imgAnime: "https://lh3.googleusercontent.com/-BlkaQFCEN84/YX01P-ZG1PI/AAAAAAAAy90/uc-TSwVDYaEICjHyz2tYeDThM4AVfaJqgCNcBGAsYHQ/s120/yamato.png",
	colorBg: "#bd3030"
},{
	imgAnime: "https://lh3.googleusercontent.com/-oxxLdQIMJSw/YX53fbkZvEI/AAAAAAAAzAI/qJTbNX1HsSQl6bgU6uA5Zp-kC9jkonzBACNcBGAsYHQ/s120/kaido-rejiu.png",
	colorBg: "#ff82a2"
}, {
	imgAnime: "https://lh3.googleusercontent.com/-WBdWoZROHsI/YX-rsPKEQoI/AAAAAAAAzDY/0R9wl6fTlFMyn5TmYY3A4j230C9a4bsbwCNcBGAsYHQ/s120/edward-newgate.png",
	colorBg: "#e12929"
},{
	imgAnime: "https://lh3.googleusercontent.com/-3IJPGi8xj0s/YX_KRI3zaYI/AAAAAAAAzEs/-PXGza_J5gEYYph96q0Q4KNi6kCF5fz5wCNcBGAsYHQ/s120/sengoku.png",
	colorBg: "#6574b4"
},{
	imgAnime: "https://1.bp.blogspot.com/-L6zjbaWc0VM/YQqZ_877g4I/AAAAAAAAv3E/k4V_f1JiP-gmKq0Hj5IItqIbjHD5mULtgCNcBGAsYHQ/s120/naruto.png",
	colorBg: "#ec7230"
},{
	imgAnime: "https://lh3.googleusercontent.com/-7_AtJFQnlbI/YX4iIqn3SKI/AAAAAAAAy_Y/39R7V8xNHAMgbfffZXgzRHYD0chaxAYOgCNcBGAsYHQ/s120/naruto.png",
	colorBg: "#f5742e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-5YSrPZS5OTQ/YQtt31nppUI/AAAAAAAAv4k/aWWMO75j2EALPqCHfLKzyFcXB6qhbP4zgCNcBGAsYHQ/s120/sasuke.png",
	colorBg: "#103555"
},{
	imgAnime: "https://lh3.googleusercontent.com/-ZOOYvt8GEwg/YYJJY8bxPfI/AAAAAAAAzLA/EXD47ePqpa8S8tyydoSkBgkpvGGwj0mmACNcBGAsYHQ/s120/sasuke.png",
	colorBg: "#6283a5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-xhj9vr_icEw/YQkNus86DjI/AAAAAAAAv1Y/T_FYJlBMT1A6AxsPEDiAfMnDbdc8nDb2gCNcBGAsYHQ/s120/kakashi.png",
	colorBg: "#626b57"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Ar1qfZgfJDM/YRSz5fI_DyI/AAAAAAAAwJ4/a103ZpEJoIUhATEfMwsQDaMdAFD53MCpgCNcBGAsYHQ/s120/sakura.png",
	colorBg: "#cc7a7f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-CS2v0BvqwBE/YRS0bnCbVzI/AAAAAAAAwKA/rXLqcIbI9pEmR7pnH-VoXGNVstDhEJ_AgCNcBGAsYHQ/s120/tusnade.png",
	colorBg: "#4c7c60"
}, {
	imgAnime: "https://1.bp.blogspot.com/-7Ddn00y0l2g/YTn3SB_1tXI/AAAAAAAAxD4/xgBQacU0qI08aywsKsHfkwNNGVi8WsCkACNcBGAsYHQ/s120/jraiya.png",
	colorBg: "#834f55"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Ff2_CyJAqrg/YTy8KQGBFcI/AAAAAAAAxG4/w5EtgEAz5zc1CJkeyD9b9xotEiQjCKnoACNcBGAsYHQ/s120/boruto.png",
	colorBg: "#1e99e7"
}, {
	imgAnime: "https://1.bp.blogspot.com/-vH8vbsblRSc/YVW7kSz8POI/AAAAAAAAxvw/REQnTj0zwz4bli7MVWc6F5Lc6WBTXiS7wCNcBGAsYHQ/s120/mitsuki.png",
	colorBg: "#599bd7"
}, {
	imgAnime: "https://1.bp.blogspot.com/-7LF01HmPHPw/YQ4JkrsdbdI/AAAAAAAAv8Q/0Qi_816Sa7UUEyKgRjXLBIoKG-LOamhTQCNcBGAsYHQ/s120/yahiko.png",
	colorBg: "#7d2727"
}, {
	imgAnime: "https://1.bp.blogspot.com/-Her8xlrrQCY/YRjYBdI8rhI/AAAAAAAAwTo/zRslu89q2TQgMRRPxWAc0z7lT_KJYpNuACNcBGAsYHQ/s120/nagato.png",
	colorBg: "#981d18"
}, {
	imgAnime: "https://1.bp.blogspot.com/-n_CBrOs73kU/YRjYbRF1xQI/AAAAAAAAwTw/9di9txxBBvAgYgbsQVlVMcpA8f4zkNBewCNcBGAsYHQ/s120/konan.png",
	colorBg: "#981d18"
}, {
	imgAnime: "https://1.bp.blogspot.com/-CKcBITDyc58/YQ4KtF_AtlI/AAAAAAAAv8Y/KJwF5uAC1mwnOD7xdKqL41yP-NJguA9AQCNcBGAsYHQ/s120/obito.png",
	colorBg: "#1c4d68"
}, {
	imgAnime: "https://1.bp.blogspot.com/-KcCCrfrbxEw/YRjY9WpdJtI/AAAAAAAAwT4/GdEcIJAcuvAkaNbj7M_xX0Nn1eFP1JHPQCNcBGAsYHQ/s120/kakuzu.png",
	colorBg: "#777"
}, {
	imgAnime: "https://1.bp.blogspot.com/-B3-VALnkvQg/YRjZa-inEQI/AAAAAAAAwUA/OFDsr0PgqRYnbVTpgVzHfrdFsIYV-SQyQCNcBGAsYHQ/s120/deidara.png",
	colorBg: "#c7a548"
}, {
	imgAnime: "https://1.bp.blogspot.com/-CWo5dbAuE4M/YQ_SFnxgO0I/AAAAAAAAwBY/keSGguTH4kM7j1x20von_KoLXUfuMUzUACNcBGAsYHQ/s120/itachi.png",
	colorBg: "#47282b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-fg756cApCdU/YRd5sMNvQHI/AAAAAAAAwQ4/3YqvC_exELkz_KE5hmJrvyk9tYz8wwvdgCNcBGAsYHQ/s120/hidan.png",
	colorBg: "#b95e57"
}, {
	imgAnime: "https://1.bp.blogspot.com/-G0-V1YZ1bn0/YRd6ZEodxuI/AAAAAAAAwRA/HWGpEL3BUEgJLXd4jR4Ri7k4oDL_Vt-5ACNcBGAsYHQ/s120/kisame.png",
	colorBg: "#b95e57"
}, {
	imgAnime: "https://1.bp.blogspot.com/-keYdneZwxjE/YRjZ72jvVfI/AAAAAAAAwUI/0TqPvxHAnhEbLruw0uCKxy_G2h1kZM0-QCNcBGAsYHQ/s120/sasori.png",
	colorBg: "#b8525b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-hQDC3aa-qK8/YRjabB3E3VI/AAAAAAAAwUQ/3shQaBOJiBUVqQmVTV5Z-WjxuKxZDbAWgCNcBGAsYHQ/s120/zetsu.png",
	colorBg: "#6f8461"
}, {
	imgAnime: "https://1.bp.blogspot.com/-iIJz2RT-k7I/YRja0oJ9b5I/AAAAAAAAwUY/3neGuO_H_uo9__RRPgLZR6i0h3S1SvfigCNcBGAsYHQ/s120/orochimaru.png",
	colorBg: "#705c4e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-1rP0v0irX9g/YQ_STpG4JgI/AAAAAAAAwBg/cGz_s3ujvGcSIjd9KgFhRkQhlhA3TqfDwCNcBGAsYHQ/s120/tenten.png",
	colorBg: "#47282b"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ofuo8FrbTyQ/YQ4_TmpZ5FI/AAAAAAAAv9Q/9s6GofFQGnwgXkkheU-ze-XRXztmAcM7ACNcBGAsYHQ/s120/kushina.png",
	colorBg: "#9c3c4c"
}, {
	imgAnime: "https://1.bp.blogspot.com/-i9e4qs57BiA/YQ5BlPo1gXI/AAAAAAAAv9c/hUbDm1fVJokZzcnd3fXFAl8LVIQHYcCjwCNcBGAsYHQ/s120/minato.png",
	colorBg: "#777"
}, {
	imgAnime: "https://1.bp.blogspot.com/-USIUbP_2vZg/YRYdjH_WWFI/AAAAAAAAwNo/5WPZALM6aewZsoWdT4uSYPzgP9M-_NEOgCNcBGAsYHQ/s120/gaara.png",
	colorBg: "#85464d"
}, {
	imgAnime: "https://1.bp.blogspot.com/-1m-EbLHrcaE/YRYeMmFZT9I/AAAAAAAAwNw/wcqubpGEAr0w-XRmabX1UAEbPOswViJ9QCNcBGAsYHQ/s120/hashirama.png",
	colorBg: "#777"
}, {
	imgAnime: "https://1.bp.blogspot.com/-tZgdLoNT5dc/YRYw78qm5II/AAAAAAAAwOw/V5jmGUQhZ6sSmN6aODnBSv-oubn2O88EACNcBGAsYHQ/s120/madara.png",
	colorBg: "#a3645d"
}, {
	imgAnime: "https://1.bp.blogspot.com/-6f-A5erlKJ4/YRYxXHvDk2I/AAAAAAAAwO4/XiSfCDQB-CYorAv4DZK8cZUpFH4CCPw9wCNcBGAsYHQ/s120/shikamaru.png",
	colorBg: "#6f7f5e"
}, {
	imgAnime: "https://1.bp.blogspot.com/-lmCYjuEEqT4/YRYyAJxY5pI/AAAAAAAAwPE/C04ktU6o9QIQHpwRC4IXUGlXVJgsMspsQCNcBGAsYHQ/s120/temari.png",
	colorBg: "#a095b5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-hQS6uQuxWTo/YRj8PN8QL7I/AAAAAAAAwVY/rFO88neKNQA4uzGHPZ1eKDcB3_ldZXk3gCNcBGAsYHQ/s120/uchiha-shisui.png",
	colorBg: "#595f41"
}, {
	imgAnime: "https://1.bp.blogspot.com/-RWk_79P5Hu4/YRj9uoKnPbI/AAAAAAAAwVo/zqNQfLLGwtMw_KlHjwnSAvrmL1J59XLvQCNcBGAsYHQ/s120/hinata-hyuga.png",
	colorBg: "#816e87"
}, {
	imgAnime: "https://1.bp.blogspot.com/-_tcUKKOmidw/YRkEYP1xAvI/AAAAAAAAwWw/W8WO76prD4QIZuytIxQQrRvkEr8TYy7VgCNcBGAsYHQ/s120/asuma.png",
	colorBg: "#74795a"
}, {
	imgAnime: "https://1.bp.blogspot.com/-ZUzK61zRQyw/YRooknSYFTI/AAAAAAAAwY0/xig7pXLJZG4D1ZUc8uipYrcYPXocvF18ACNcBGAsYHQ/s120/tobirama.png",
	colorBg: "#3d6499"
}, {
	imgAnime: "https://1.bp.blogspot.com/-_uJ-8W6TcNA/YQ5JiTVjC2I/AAAAAAAAv-Q/ng_PK2jqAxUzV3AaT6xvJEYmaHuYRsmUwCNcBGAsYHQ/s120/songoku.png",
	colorBg: "#f69e3f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-DHKmKVOWB5E/YQ5KOhqCUAI/AAAAAAAAv-Y/UpV2SArQMQwTy1lB6loC83m9vzjsIB0rwCNcBGAsYHQ/s120/vegeta.png",
	colorBg: "#223f89"
}, {
	imgAnime: "https://1.bp.blogspot.com/-mx4yeGDk1cM/YQ5KtIpbJJI/AAAAAAAAv-g/wbWhxO56coIJeWejlmSttEJOaB-4IqFUgCNcBGAsYHQ/s120/gohan.png",
	colorBg: "#326ee3"
}, {
	imgAnime: "https://1.bp.blogspot.com/-rMrX5g2G9LI/YQ5MpVpVtaI/AAAAAAAAv-o/M4DDulBEPl8O0GPc4OQs8nVw2cQ06MuvgCNcBGAsYHQ/s120/black-goku.png",
	colorBg: "#2c2b2f"
}, {
	imgAnime: "https://1.bp.blogspot.com/-UQDKkhQBO1g/YQj2sRzBrRI/AAAAAAAAv04/tEpL58TzhB4gMJLp0GmebOs9o-Wq76wcgCNcBGAsYHQ/s120/taki.png",
	colorBg: "#539bc5"
}, {
	imgAnime: "https://1.bp.blogspot.com/-SHa2sh1AzeY/YQj3OVQhWHI/AAAAAAAAv1A/CfDtQBtC8vUq20DMHKzhSyRk5u2ycuwfwCNcBGAsYHQ/s120/mitsuha.png",
	colorBg: "#8f7fa4"
}];
console.log(Object.keys(dsAnime).length);